<?php

use Illuminate\Support\Facades\File;

/**
 * infrastructure/scripts/mail-identity — the reviewed mail identity of the host
 * (mail-outbound.json) and of each production target (mail-identity.json): the
 * DKIM key a target signs with, the DNS records that publish it, and the proof,
 * from the host, that public DNS says exactly that.
 *
 * Every test runs the shipped script. Keys are real, generated by OpenSSL, and
 * the public key it derives is checked against PHP's own OpenSSL binding. DNS is
 * a stub that answers in the exact presentation format `dig` prints; nothing
 * here queries the network, and nothing anywhere sends mail.
 *
 * The real tits-guru identity is reviewed here, and stays inert: tits-guru is
 * still held and planned, and the host still has direct delivery disabled.
 */
/** A refusal: non-zero, and this reason on stderr. */
function expectMailIdentityRefusal(array $run, string $reason): void
{
    expect($run['status'])->not->toBe(0, "expected a refusal for: {$reason}\n{$run['stdout']}");
    expect($run['stdout'])->toBe('', 'a refused run printed something on stdout');
    expect(str_contains($run['stderr'], $reason))->toBeTrue("refusal reason not found:\n  {$reason}\nstderr was:\n{$run['stderr']}");
}

// =============================================================================
// THE REVIEWED IDENTITY
// =============================================================================

it('validates the real host and target identity contracts', function () {
    $run = mailIdentityRun(['validate']);

    expect($run['status'])->toBe(0, $run['stderr']);
    expect($run['stdout'])->toContain('mail identity is valid');

    // mta1.tits.guru is the reviewed host identity, and direct delivery stays
    // disabled on the host.
    expect(json_decode(File::get(base_path('infrastructure/config/mail-outbound.json')), true))
        ->toBe(['schema_version' => 1, 'direct' => ['enabled' => false, 'mta_hostname' => 'mta1.tits.guru']]);

    // rg1, RSA-SHA256, 2048 bits; DMARC p=none with strict alignment, and no
    // report address anywhere.
    expect(json_decode(File::get(base_path('infrastructure/config/mail-identity.json')), true))->toBe([
        'schema_version' => 1,
        'targets' => [
            'tits-guru' => [
                'dkim' => ['selector' => 'rg1', 'algorithm' => 'rsa-sha256', 'minimum_key_bits' => 2048],
                'dmarc' => ['policy' => 'none', 'adkim' => 'strict', 'aspf' => 'strict'],
            ],
        ],
    ]);

    expect(File::get(base_path('infrastructure/config/mail-identity.json')))
        ->not->toContain('rua')
        ->not->toContain('@')
        ->not->toContain('mail_domain')
        ->not->toContain('tits.guru');
});

it('keeps the real target held and planned, and the host without an outbound route', function () {
    $registry = json_decode(File::get(base_path('infrastructure/config/deployment-targets.json')), true);
    $routing = json_decode(File::get(base_path('infrastructure/config/mail-routing.json')), true);

    expect($registry['targets']['tits-guru']['lifecycle'])->toBe('planned');
    expect($routing['targets']['tits-guru']['delivery_mode'])->toBe('held');
    expect(json_decode(File::get(base_path('infrastructure/config/mail-outbound.json')), true)['direct']['enabled'])->toBeFalse();

    // The production environment is not touched by an identity.
    foreach (['production.env.example', 'tits-guru.env.example'] as $template) {
        $values = envFileValues("infrastructure/templates/environment/{$template}");

        foreach (['MAIL_MAILER', 'MAIL_HOST', 'MAIL_PORT', 'MAIL_FROM_ADDRESS'] as $key) {
            expect($values[$key] ?? '')->toBe('', "{$template} sets {$key}");
        }
    }
});

it('derives tits-guru\'s key destination from its ID and reviewed selector, deferred while its mail is held', function () {
    $run = mailIdentityRun(['dkim-key', '--target', 'tits-guru']);

    expect($run['status'])->toBe(0, $run['stderr']);
    expect($run['stdout'])->toBe("deferred\t/etc/opendkim/keys/tits-guru/rg1.private\t2048\n");

    // A target with no production identity has no key at all.
    expect(mailIdentityRun(['dkim-key', '--target', 'staging-main'])['stdout'])->toBe("none\n");
});

it('derives a target it has never heard of the same way, and requires its key once it is outbound', function () {
    $scratch = mailIdentityScratch();

    try {
        $held = mailIdentityRun(['dkim-key', '--target', 'demo-shop', ...mailIdentityFixtureConfig($scratch.'/config')]);
        expect($held['stdout'])->toBe("deferred\t/etc/opendkim/keys/demo-shop/shop2026.private\t2048\n");

        $outbound = mailIdentityRun(['dkim-key', '--target', 'demo-shop', ...mailIdentityFixtureConfig($scratch.'/config', [
            'mode' => 'outbound',
            'outbound' => ['schema_version' => 1, 'direct' => ['enabled' => true, 'mta_hostname' => 'mta1.example.net']],
        ])]);
        expect($outbound['stdout'])->toBe("required\t/etc/opendkim/keys/demo-shop/shop2026.private\t2048\n");
    } finally {
        removeScratchDir($scratch);
    }
});

it('names no target, domain, selector or host anywhere in its implementation', function () {
    $source = File::get(mailIdentityScript());

    foreach (['tits-guru', 'tits.guru', 'rg1', 'mta1', 'demo-shop', 'staging-main', 'staging.invalid', '203.0.113'] as $name) {
        expect(str_contains($source, $name))->toBeFalse("mail-identity names {$name}");
    }

    // The policy reaches it only through mail-routing's render, and nothing from
    // a contract is ever evaluated as code.
    $code = executableSourceLines($source);
    expect($code)
        ->toContain('"${MAIL_ROUTING_CLI}" render-plan --file "${ROUTING_FILE}" --registry "${REGISTRY_FILE}"')
        ->not->toContain('eval ')
        ->not->toContain('bash -c');
});

it('changes nothing: no file, no service, no record, no mail', function () {
    $code = executableSourceLines(File::get(mailIdentityScript()));

    // Commands, as whole words: "-outform" is not rm, and "installed" in a
    // message is not install.
    foreach (['install', 'mkdir', 'chmod', 'chown', 'mv', 'rm', 'tee', 'cp', 'mktemp', 'systemctl', 'postconf', 'postfix', 'postsuper', 'sendmail', 'nsupdate', 'curl', 'wget', 'ssh', 'scp', 'sudo', 'genpkey', 'genrsa', 'req'] as $command) {
        expect(preg_match('/(?<![\w-])'.preg_quote($command, '/').'(?![\w-])/', $code))->toBe(0, "mail-identity runs {$command}");
    }

    // A key is never printed in any form: no text dump, no cat, no echo of it.
    foreach (['-text -in', 'cat "${path}"', 'cat "$1"', '-noout -text -in'] as $leak) {
        expect(str_contains($code, $leak))->toBeFalse("mail-identity could print a key with {$leak}");
    }
});

it('is repository tooling, never installed onto a host', function () {
    expect(repositoryOnlyScriptNames())->toContain('mail-identity');
    expect(requiredCliManifestNames())->not->toContain('mail-identity');
    expect(executableSourceLines(File::get(base_path('infrastructure/scripts/install-target-operations'))))
        ->not->toContain('mail-identity');
});

// =============================================================================
// THE IDENTITY CONTRACT IS CLOSED
// =============================================================================

it('refuses an identity whose target the registry does not have, or that is not a production one', function (array $identity, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config');
        $document = json_decode((string) file_get_contents($scratch.'/config/mail-identity.json'), true);
        $document['targets'] = [...$document['targets'], ...$identity];
        file_put_contents($scratch.'/config/mail-identity.json', mailRoutingJson($document));

        expectMailIdentityRefusal(mailIdentityRun(['validate', ...$files]), $reason);
    } finally {
        removeScratchDir($scratch);
    }
})->with([
    'an unknown target' => [['food-guru' => mailIdentityDemoShopIdentity()], 'food-guru: not a target in the deployment registry'],
    'a staging target' => [['staging-main' => mailIdentityDemoShopIdentity()], 'staging-main: environment_class staging has no production mail identity — a staging target captures its mail and never signs it'],
    'a malformed target ID' => [['Demo_Shop' => mailIdentityDemoShopIdentity()], 'invalid target ID "Demo_Shop"'],
]);

it('refuses a DKIM selector that is not one safe lowercase DNS label', function (mixed $selector) {
    $scratch = mailIdentityScratch();

    try {
        $identity = mailIdentityDemoShopIdentity();
        $identity['dkim']['selector'] = $selector;

        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity])]),
            'demo-shop: dkim.selector must be one lowercase DNS label',
        );
    } finally {
        removeScratchDir($scratch);
    }
})->with([
    'uppercase' => 'RG1',
    'two labels' => 'rg1.mail',
    'an underscore' => 'rg_1',
    'a leading hyphen' => '-rg1',
    'a trailing hyphen' => 'rg1-',
    'empty' => '',
    'longer than a label' => str_repeat('a', 64),
    'whitespace' => 'rg 1',
    'a number' => 1,
]);

it('accepts exactly rsa-sha256 as the DKIM algorithm', function (mixed $algorithm) {
    $scratch = mailIdentityScratch();

    try {
        $identity = mailIdentityDemoShopIdentity();
        $identity['dkim']['algorithm'] = $algorithm;

        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity])]),
            'demo-shop: dkim.algorithm must be one of rsa-sha256, got '.json_encode($algorithm),
        );
    } finally {
        removeScratchDir($scratch);
    }
})->with(['rsa-sha1', 'ed25519-sha256', 'RSA-SHA256', 'rsa', '']);

it('refuses a minimum key size below 2048 bits, or one that is not a whole number of bits', function (mixed $bits) {
    $scratch = mailIdentityScratch();

    try {
        $identity = mailIdentityDemoShopIdentity();
        $identity['dkim']['minimum_key_bits'] = $bits;

        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity])]),
            'demo-shop: dkim.minimum_key_bits must be an integer from 2048 to 4096',
        );
    } finally {
        removeScratchDir($scratch);
    }
})->with([1024, 2047, 0, -2048, 2048.5, '2048', 8192, null]);

it('accepts every reviewed key size from 2048 to 4096 bits', function (int $bits) {
    $scratch = mailIdentityScratch();

    try {
        $identity = mailIdentityDemoShopIdentity();
        $identity['dkim']['minimum_key_bits'] = $bits;

        $run = mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity])]);
        expect($run['status'])->toBe(0, $run['stderr']);
    } finally {
        removeScratchDir($scratch);
    }
})->with([2048, 3072, 4096]);

it('refuses a DMARC policy outside the reviewed vocabulary', function (array $dmarc, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        $identity = mailIdentityDemoShopIdentity();
        $identity['dmarc'] = [...$identity['dmarc'], ...$dmarc];

        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity])]),
            $reason,
        );
    } finally {
        removeScratchDir($scratch);
    }
})->with([
    'an unknown policy' => [['policy' => 'monitor'], 'demo-shop: dmarc.policy must be one of none, quarantine, reject, got "monitor"'],
    'a DNS tag value for alignment' => [['adkim' => 's'], 'demo-shop: dmarc.adkim must be one of relaxed, strict, got "s"'],
    'an empty alignment' => [['aspf' => ''], 'demo-shop: dmarc.aspf must be one of relaxed, strict, got ""'],
    'a report address nobody reviewed' => [['rua' => 'mailto:dmarc@demo-shop.example'], 'demo-shop: dmarc must be exactly {policy, adkim, aspf}, found ["adkim","aspf","policy","rua"]'],
]);

it('never repeats what mail-routing is the authority for, and holds no secret', function (array $set, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => [...mailIdentityDemoShopIdentity(), ...$set]])]),
            $reason,
        );
    } finally {
        removeScratchDir($scratch);
    }
})->with([
    'the mail domain' => [['mail_domain' => 'demo-shop.example'], 'demo-shop: identity must be exactly {dkim, dmarc}, found ["dkim","dmarc","mail_domain"] — the mail domain, sender, bounce and reply domains stay in mail-routing.json'],
    'the sender' => [['default_from' => 'hello@demo-shop.example'], 'identity must be exactly {dkim, dmarc}'],
    'the submission port' => [['submission' => ['host' => '127.0.0.1', 'port' => 2599]], 'identity must be exactly {dkim, dmarc}'],
    'the delivery mode' => [['delivery_mode' => 'outbound'], 'identity must be exactly {dkim, dmarc}'],
    'a private key' => [['private_key' => 'MIIE...'], 'the identity contract holds a secret-like property name "private_key"'],
]);

it('refuses an outbound target that has no reviewed identity', function () {
    $scratch = mailIdentityScratch();

    try {
        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', [
                'mode' => 'outbound',
                'identity' => null,
                'outbound' => ['schema_version' => 1, 'direct' => ['enabled' => true, 'mta_hostname' => 'mta1.example.net']],
            ])]),
            'demo-shop: delivers outbound, so it needs a reviewed DKIM and DMARC identity in mail-identity.json',
        );
    } finally {
        removeScratchDir($scratch);
    }
});

it('refuses an identity document that is not exactly one reviewed object', function (string $document, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config');
        file_put_contents($scratch.'/config/mail-identity.json', $document);

        expectMailIdentityRefusal(mailIdentityRun(['validate', ...$files]), $reason);
    } finally {
        removeScratchDir($scratch);
    }
})->with([
    'another schema' => ['{"schema_version": 2, "targets": {}}', 'unsupported mail identity schema_version: 2 (expected 1)'],
    'not JSON' => ['{"schema_version": 1,', 'the mail identity contract is not valid JSON'],
    'a key declared twice' => ['{"schema_version": 1, "targets": {"tits-guru": {}, "tits-guru": {}}}', 'declares the same key twice in one object'],
    'an extra property' => ['{"schema_version": 1, "comment": "x", "targets": {}}', 'the mail identity contract must be exactly {schema_version, targets}'],
    'a control character' => ['{"schema_version": 1, "targets": {"tits-guru": {"dkim": {"selector": "rg1\\n"}}}}', 'must not contain control characters'],
]);

it('accepts a reviewed MTA hostname while direct delivery stays disabled, and judges it all the same', function () {
    $scratch = mailIdentityScratch();

    try {
        // The real shape: named and disabled.
        $files = mailIdentityFixtureConfig($scratch.'/config', ['outbound' => ['schema_version' => 1, 'direct' => ['enabled' => false, 'mta_hostname' => 'mta1.example.net']]]);
        expect(mailIdentityRun(['validate', ...$files])['status'])->toBe(0);

        // A disabled hostname is still a reviewed value, so it is still judged.
        $files = mailIdentityFixtureConfig($scratch.'/config', ['outbound' => ['schema_version' => 1, 'direct' => ['enabled' => false, 'mta_hostname' => 'mta1.rateguru.invalid']]]);
        expectMailIdentityRefusal(mailIdentityRun(['validate', ...$files]), 'direct.mta_hostname "mta1.rateguru.invalid" is under the reserved .invalid domain');
    } finally {
        removeScratchDir($scratch);
    }
});

// =============================================================================
// PRIVATE KEYS: JUDGED, NEVER SHOWN
// =============================================================================

it('accepts an unencrypted RSA private key of at least the reviewed size, PKCS#8 or PKCS#1', function (string $kind, int $bits) {
    $run = mailIdentityRun(['check-key', '--file', mailIdentityKey($kind)]);

    expect($run['status'])->toBe(0, $run['stderr']);
    expect($run['stdout'])->toContain("usable: an unencrypted {$bits}-bit RSA private key");
    expectNoKeyMaterial($run['stdout'].$run['stderr'], mailIdentityKey($kind));
})->with([
    'PKCS#8, 2048 bits' => ['rsa2048', 2048],
    'PKCS#1, 2048 bits' => ['rsa2048-pkcs1', 2048],
    'PKCS#8, 3072 bits' => ['rsa3072', 3072],
]);

it('refuses everything that is not a usable DKIM private key, without ever showing it', function (string $kind, string $reason) {
    $run = mailIdentityRun(['check-key', '--file', mailIdentityKey($kind)]);

    expectMailIdentityRefusal($run, "not a usable DKIM private key: {$reason}");
    expectNoKeyMaterial($run['stdout'].$run['stderr'], mailIdentityKey($kind));
})->with([
    'not PEM at all' => ['junk', 'it is not PEM'],
    'a public key' => ['public', 'it is a public key, not a private key'],
    'a certificate' => ['certificate', 'it is a certificate, not a private key'],
    'a key with a certificate beside it' => ['key-and-certificate', 'it is a certificate, not a private key'],
    'a passphrase-protected key' => ['encrypted', 'it is passphrase-protected'],
    'RSA below 2048 bits' => ['rsa1024', 'it is a 1024-bit RSA key, below the reviewed minimum of 2048 bits'],
    'an EC key' => ['ec', 'it is not a usable RSA private key'],
    'an Ed25519 key' => ['ed25519', 'it is not a usable RSA private key'],
]);

it('holds a key to the minimum the identity reviews, not merely to 2048 bits', function () {
    expectMailIdentityRefusal(
        mailIdentityRun(['check-key', '--file', mailIdentityKey('rsa2048'), '--min-bits', '3072']),
        'it is a 2048-bit RSA key, below the reviewed minimum of 3072 bits',
    );
    expect(mailIdentityRun(['check-key', '--file', mailIdentityKey('rsa3072'), '--min-bits', '3072'])['status'])->toBe(0);
});

it('refuses a key reached through a symlink, or that is not a regular file', function () {
    $scratch = mailIdentityScratch();

    try {
        symlink(mailIdentityKey('rsa2048'), $scratch.'/link.pem');

        expectMailIdentityRefusal(mailIdentityRun(['check-key', '--file', $scratch.'/link.pem']), 'it is a symlink');
        expectMailIdentityRefusal(mailIdentityRun(['check-key', '--file', $scratch.'/fs']), 'it is not a regular file');
        expectMailIdentityRefusal(mailIdentityRun(['check-key', '--file', $scratch.'/absent.pem']), 'it does not exist');
    } finally {
        removeScratchDir($scratch);
    }
});

// =============================================================================
// THE DNS TO PUBLISH
// =============================================================================

it('prints exactly the records to publish, deriving the DKIM public key from the installed private key', function () {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $env = mailIdentityDnsHost($scratch, []);

        $run = mailIdentityRun(['show-dns', '--target', 'tits-guru'], $env);
        expect($run['status'])->toBe(0, $run['stderr']);

        $text = preg_replace('/\s+/', ' ', $run['stdout']);
        $public = mailIdentityPublicKey($key);

        expect($text)
            ->toContain('hostname mta1.tits.guru (direct delivery disabled on this host)')
            ->toContain('A mta1.tits.guru -> 203.0.113.10')
            ->toContain('PTR 203.0.113.10 -> mta1.tits.guru')
            ->toContain('TXT rg1._domainkey.tits.guru v=DKIM1; k=rsa; p='.$public)
            ->toContain('TXT tits.guru v=spf1 ip4:203.0.113.10 -all')
            ->toContain('TXT _dmarc.tits.guru v=DMARC1; p=none; adkim=s; aspf=s');

        expectNoKeyMaterial($run['stdout'].$run['stderr'], $key);

        // Deterministic: the same key and host print the same plan.
        expect(mailIdentityRun(['show-dns', '--target', 'tits-guru'], $env)['stdout'])->toBe($run['stdout']);
    } finally {
        removeScratchDir($scratch);
    }
});

it('prints the same records as JSON, with nothing but public values', function () {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $run = mailIdentityRun(['show-dns', '--target', 'tits-guru', '--json'], mailIdentityDnsHost($scratch, []));

        expect($run['status'])->toBe(0, $run['stderr']);
        $plan = json_decode($run['stdout'], true, 512, JSON_THROW_ON_ERROR);

        expect($plan['mta'])->toBe(['direct_delivery_enabled' => false, 'hostname' => 'mta1.tits.guru', 'ipv4' => '203.0.113.10']);
        expect($plan['dkim']['key_status'])->toBe('usable');
        expect($plan['records'])->toBe([
            ['name' => 'mta1.tits.guru', 'purpose' => 'A', 'type' => 'A', 'value' => '203.0.113.10'],
            ['name' => '203.0.113.10', 'purpose' => 'PTR', 'type' => 'PTR', 'value' => 'mta1.tits.guru'],
            ['name' => 'rg1._domainkey.tits.guru', 'purpose' => 'DKIM', 'type' => 'TXT', 'value' => 'v=DKIM1; k=rsa; p='.mailIdentityPublicKey($key)],
            ['name' => 'tits.guru', 'purpose' => 'SPF', 'type' => 'TXT', 'value' => 'v=spf1 ip4:203.0.113.10 -all'],
            ['name' => '_dmarc.tits.guru', 'purpose' => 'DMARC', 'type' => 'TXT', 'value' => 'v=DMARC1; p=none; adkim=s; aspf=s'],
        ]);

        expectNoKeyMaterial($run['stdout'], $key);
    } finally {
        removeScratchDir($scratch);
    }
});

it('says in its JSON whether the key is usable, absent or unusable, and leaves an underivable value empty', function () {
    $scratch = mailIdentityScratch();

    try {
        $plan = fn (): array => json_decode(mailIdentityRun(['show-dns', '--target', 'tits-guru', '--json'], mailIdentityDnsHost($scratch, []))['stdout'], true, 512, JSON_THROW_ON_ERROR);
        $dkim = fn (array $plan): mixed => collect($plan['records'])->firstWhere('purpose', 'DKIM')['value'];

        expect($plan()['dkim']['key_status'])->toBe('absent')
            ->and($dkim($plan()))->toBeNull();

        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        file_put_contents($key, (string) file_get_contents(mailIdentityKey('rsa1024')));

        expect($plan()['dkim']['key_status'])->toBe('unusable')
            ->and($dkim($plan()))->toBeNull();

        file_put_contents($key, (string) file_get_contents(mailIdentityKey('rsa2048')));

        expect($plan()['dkim']['key_status'])->toBe('usable')
            ->and($dkim($plan()))->toStartWith('v=DKIM1; k=rsa; p=');
    } finally {
        removeScratchDir($scratch);
    }
});

it('derives the public key from a key the operator holds, before it is installed anywhere', function () {
    // The order an operator works in: create the key, publish its public half,
    // then supply it. show-dns reads a key file named on the command line and
    // still prints only the public half.
    $scratch = mailIdentityScratch();

    try {
        $run = mailIdentityRun(['show-dns', '--target', 'tits-guru', '--key', mailIdentityKey('rsa2048-pkcs1'), '--ipv4', '198.51.100.7']);

        expect($run['status'])->toBe(0, $run['stderr']);
        expect(preg_replace('/\s+/', ' ', $run['stdout']))
            ->toContain('p='.mailIdentityPublicKey(mailIdentityKey('rsa2048')))
            ->toContain('v=spf1 ip4:198.51.100.7 -all');
        expectNoKeyMaterial($run['stdout'].$run['stderr'], mailIdentityKey('rsa2048-pkcs1'));
    } finally {
        removeScratchDir($scratch);
    }
});

it('says what is still pending instead of inventing a key or an address', function () {
    $scratch = mailIdentityScratch();

    try {
        $run = mailIdentityRun(['show-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, [], null));

        expect($run['status'])->toBe(0, $run['stderr']);
        expect($run['stdout'])
            ->toContain('<pending: the installed key /etc/opendkim/keys/tits-guru/rg1.private is not usable — it does not exist>')
            ->toContain('<this host IPv4: run on the mail host, or pass --ipv4>')
            ->not->toContain('v=DKIM1');

        // A weak key is named as such, and never published.
        mailIdentityInstallKey($scratch, 'tits-guru', 'rg1', 'rsa1024');
        expect(mailIdentityRun(['show-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, []))['stdout'])
            ->toContain('below the reviewed minimum of 2048 bits')
            ->not->toContain('v=DKIM1; k=rsa; p=');

        expectMailIdentityRefusal(mailIdentityRun(['show-dns', '--target', 'staging-main']), 'staging-main has no mail identity');
    } finally {
        removeScratchDir($scratch);
    }
});

// =============================================================================
// VERIFYING PUBLIC DNS
// =============================================================================

it('verifies correctly published DNS, joining a long DKIM record a provider split into chunks', function () {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $dns = mailIdentityGoodDns(mailIdentityPublicKey($key));

        // Proof the record really is split, with whitespace between the chunks.
        expect(substr_count($dns['TXT rg1._domainkey.tits.guru'][0], '" "'))->toBeGreaterThan(0);

        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, $dns));

        expect($run['status'])->toBe(0, $run['stdout'].$run['stderr']);
        expect($run['stdout'])
            ->toContain('PASS   a          mta1.tits.guru A includes this host\'s address 203.0.113.10')
            ->toContain('PASS   ptr        203.0.113.10 PTR is mta1.tits.guru')
            ->toContain('PASS   spf        tits.guru SPF authorizes exactly this host (203.0.113.10) and fails everything else')
            ->toContain('PASS   dkim       rg1._domainkey.tits.guru publishes exactly the public key of the installed private key')
            ->toContain('PASS   dmarc      _dmarc.tits.guru publishes exactly the reviewed policy')
            ->toContain('DNS VERIFIED: YES');
        expectNoKeyMaterial($run['stdout'].$run['stderr'], $key);
    } finally {
        removeScratchDir($scratch);
    }
});

it('accepts a DKIM value a DNS panel published with whitespace inside the key, as verifiers do', function () {
    // RFC 6376 lets the base64 in p= carry folding whitespace, and some DNS
    // panels insert spaces into a long value; a verifier ignores them.
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $dns = mailIdentityGoodDns(mailIdentityPublicKey($key));
        $dns['TXT rg1._domainkey.tits.guru'] = ['"v=DKIM1;  k=rsa ;  p='.implode(' ', str_split(mailIdentityPublicKey($key), 64)).'"'];

        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, $dns));

        expect($run['status'])->toBe(0, $run['stdout']);
        expect($run['stdout'])->toContain('PASS   dkim       rg1._domainkey.tits.guru publishes exactly the public key of the installed private key');
    } finally {
        removeScratchDir($scratch);
    }
});

it('refuses every way public DNS can disagree with the reviewed identity', function (array $changes, string|false|null $ipv4, string $check, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $dns = mailIdentityGoodDns(mailIdentityPublicKey($key));

        // Each change replaces one answer whole; null removes it, and
        // OTHER_KEY stands for the public key of a different private key.
        foreach ($changes as $question => $answer) {
            if ($answer === null) {
                unset($dns[$question]);

                continue;
            }

            $dns[$question] = array_map(
                static fn (mixed $value): mixed => is_string($value) ? str_replace('OTHER_KEY', mailIdentityPublicKey(mailIdentityKey('rsa3072')), $value) : $value,
                $answer,
            );
        }

        $run = mailIdentityRun(
            ['verify-dns', '--target', 'tits-guru'],
            mailIdentityDnsHost($scratch, $dns, $ipv4 === false ? '203.0.113.10' : $ipv4),
        );

        expect($run['status'])->not->toBe(0, $run['stdout']);
        expect($run['stdout'])
            ->toMatch('/^  FAIL   '.preg_quote($check, '/').' +.*'.preg_quote($reason, '/').'/m')
            ->toContain('DNS VERIFIED: NO')
            ->not->toContain('DNS VERIFIED: YES');
        expectNoKeyMaterial($run['stdout'].$run['stderr'], $key);
    } finally {
        removeScratchDir($scratch);
    }
})->with([
    'an A record elsewhere' => [['A mta1.tits.guru' => ['198.51.100.9']], false, 'a', 'mta1.tits.guru A is [198.51.100.9], which does not include this host\'s address 203.0.113.10'],
    'no A record' => [['A mta1.tits.guru' => null], false, 'a', 'mta1.tits.guru has no A record (NXDOMAIN)'],
    'a PTR naming something else' => [['PTR 10.113.0.203.in-addr.arpa' => ['ip-203-0-113-10.provider.example.']], false, 'ptr', '203.0.113.10 PTR is ip-203-0-113-10.provider.example, not mta1.tits.guru'],
    'no PTR' => [['PTR 10.113.0.203.in-addr.arpa' => null], false, 'ptr', '203.0.113.10 has no PTR record'],
    'two PTR records' => [['PTR 10.113.0.203.in-addr.arpa' => ['mta1.tits.guru.', 'other.example.']], false, 'ptr', 'has 2 PTR records'],
    'two SPF policies' => [['TXT tits.guru' => ['"v=spf1 ip4:203.0.113.10 -all"', '"v=spf1 include:_spf.provider.example ~all"']], false, 'spf', 'tits.guru publishes 2 SPF policies — receivers treat more than one as a permanent error'],
    'no SPF policy' => [['TXT tits.guru' => ['"site-verification=abc123"']], false, 'spf', 'tits.guru publishes no SPF policy — publish exactly one TXT record: v=spf1 ip4:203.0.113.10 -all'],
    'a soft-failing SPF' => [['TXT tits.guru' => ['"v=spf1 ip4:203.0.113.10 ~all"']], false, 'spf', 'tits.guru SPF is "v=spf1 ip4:203.0.113.10 ~all", not the reviewed'],
    'SPF for another address' => [['TXT tits.guru' => ['"v=spf1 ip4:198.51.100.9 -all"']], false, 'spf', 'not the reviewed "v=spf1 ip4:203.0.113.10 -all"'],
    'a DKIM record for another key' => [['TXT rg1._domainkey.tits.guru' => ['"v=DKIM1; k=rsa; p=OTHER_KEY"']], false, 'dkim', 'publishes a different public key than the installed private key derives'],
    'no DKIM record' => [['TXT rg1._domainkey.tits.guru' => null], false, 'dkim', 'rg1._domainkey.tits.guru has no TXT record'],
    'a DKIM record of another key type' => [['TXT rg1._domainkey.tits.guru' => ['"v=DKIM1; k=ed25519; p=abc"']], false, 'dkim', 'rg1._domainkey.tits.guru has k=ed25519, not k=rsa'],
    'a DKIM record in testing mode' => [['TXT rg1._domainkey.tits.guru' => ['"v=DKIM1; t=y; k=rsa; p=abc"']], false, 'dkim', 'must carry exactly the tags v, k and p, found: k p t v'],
    'two DKIM records' => [['TXT rg1._domainkey.tits.guru' => ['"v=DKIM1; k=rsa; p=OTHER_KEY"', '"v=DKIM1; k=rsa; p=abc"']], false, 'dkim', 'has 2 TXT records — a selector publishes exactly one key'],
    'a rejecting DMARC policy' => [['TXT _dmarc.tits.guru' => ['"v=DMARC1; p=reject; adkim=s; aspf=s"']], false, 'dmarc', '_dmarc.tits.guru has p=reject, not the reviewed p=none'],
    'relaxed DKIM alignment' => [['TXT _dmarc.tits.guru' => ['"v=DMARC1; p=none; adkim=r; aspf=s"']], false, 'dmarc', 'has adkim=r, not the reviewed adkim=s'],
    'a report address nobody reviewed' => [['TXT _dmarc.tits.guru' => ['"v=DMARC1; p=none; adkim=s; aspf=s; rua=mailto:x@tits.guru"']], false, 'dmarc', 'must carry exactly v, p, adkim and aspf'],
    'two DMARC policies' => [['TXT _dmarc.tits.guru' => ['"v=DMARC1; p=none; adkim=s; aspf=s"', '"v=DMARC1; p=none"']], false, 'dmarc', 'publishes 2 DMARC policies — exactly one is allowed'],
    'no DMARC policy' => [['TXT _dmarc.tits.guru' => null], false, 'dmarc', '_dmarc.tits.guru publishes no DMARC policy — publish exactly: v=DMARC1; p=none; adkim=s; aspf=s'],
    'neither public resolver answers' => [['TXT tits.guru' => ['exit' => 9]], false, 'spf', 'the DNS query for TXT tits.guru to public resolver 1.1.1.1 failed (dig exit 9); the DNS query for TXT tits.guru to public resolver 8.8.8.8 failed (dig exit 9)'],
    'a server failure at both' => [['TXT _dmarc.tits.guru' => ['status' => 'SERVFAIL']], false, 'dmarc', 'the DNS query for TXT _dmarc.tits.guru to public resolver 1.1.1.1 was answered SERVFAIL'],
    'a refused query at both' => [['A mta1.tits.guru' => ['status' => 'REFUSED']], false, 'a', 'was answered REFUSED'],
    'a host behind NAT' => [[], '10.0.0.5', 'address', 'this host sends from 10.0.0.5, which is not a public address'],
    'a host with no route' => [[], null, 'address', 'this host has no IPv4 route to the Internet'],
]);

it('cannot pass without a usable installed key, whatever DNS says', function () {
    $scratch = mailIdentityScratch();

    try {
        $dns = mailIdentityGoodDns(mailIdentityPublicKey(mailIdentityKey('rsa2048')));

        // Absent.
        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, $dns));
        expect($run['status'])->not->toBe(0);
        expect($run['stdout'])
            ->toContain('FAIL   key        the DKIM private key /etc/opendkim/keys/tits-guru/rg1.private is not usable: it does not exist')
            ->toContain('there is no valid installed private key to compare it with');

        // Too weak, even with a record that matches it.
        $weak = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1', 'rsa1024');
        $dns['TXT rg1._domainkey.tits.guru'] = ['"v=DKIM1; k=rsa; p='.mailIdentityPublicKey($weak).'"'];
        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, $dns));
        expect($run['status'])->not->toBe(0);
        expect($run['stdout'])->toContain('below the reviewed minimum of 2048 bits')->toContain('DNS VERIFIED: NO');
    } finally {
        removeScratchDir($scratch);
    }
});

it('verifies a target it has never heard of against its own domain, selector and the host\'s name', function () {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config', ['outbound' => ['schema_version' => 1, 'direct' => ['enabled' => false, 'mta_hostname' => 'mta1.example.net']]]);
        $key = mailIdentityInstallKey($scratch, 'demo-shop', 'shop2026', 'rsa3072');

        $run = mailIdentityRun(
            ['verify-dns', '--target', 'demo-shop', ...$files],
            mailIdentityDnsHost($scratch, mailIdentityGoodDns(mailIdentityPublicKey($key), '203.0.113.10', 'demo-shop.example', 'shop2026', 'mta1.example.net')),
        );

        expect($run['status'])->toBe(0, $run['stdout'].$run['stderr']);
        expect($run['stdout'])->toContain('shop2026._domainkey.demo-shop.example publishes exactly the public key')->toContain('DNS VERIFIED: YES');
    } finally {
        removeScratchDir($scratch);
    }
});

it('only reads: verifying DNS writes nothing and asks both public resolvers nothing but the five records', function () {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $env = mailIdentityDnsHost($scratch, mailIdentityGoodDns(mailIdentityPublicKey($key)));

        $tree = static function () use ($scratch): array {
            $files = [];
            foreach (File::allFiles($scratch.'/fs', true) as $file) {
                $files[$file->getRelativePathname()] = [hash_file('sha256', $file->getPathname()), $file->getPerms()];
            }
            ksort($files);

            return $files;
        };

        $before = $tree();
        expect(mailIdentityRun(['verify-dns', '--target', 'tits-guru'], $env)['status'])->toBe(0);
        expect($tree())->toBe($before);

        // Each record asked of Cloudflare and then Google, by address; never of
        // the host's own resolver.
        expect(mailIdentityDnsQueries($scratch))->toBe([
            '1.1.1.1 A mta1.tits.guru',
            '8.8.8.8 A mta1.tits.guru',
            '1.1.1.1 PTR 10.113.0.203.in-addr.arpa',
            '8.8.8.8 PTR 10.113.0.203.in-addr.arpa',
            '1.1.1.1 TXT tits.guru',
            '8.8.8.8 TXT tits.guru',
            '1.1.1.1 TXT rg1._domainkey.tits.guru',
            '8.8.8.8 TXT rg1._domainkey.tits.guru',
            '1.1.1.1 TXT _dmarc.tits.guru',
            '8.8.8.8 TXT _dmarc.tits.guru',
        ]);
    } finally {
        removeScratchDir($scratch);
    }
});

// =============================================================================
// PUBLIC DNS IS WHAT TWO INDEPENDENT PUBLIC RESOLVERS BOTH ANSWER
// =============================================================================

it('passes on a host whose own resolver still answers a stale local PTR, because it never asks it', function () {
    // The production false negative: the host's resolver answers the reverse
    // name from local policy with the provider's old names, while public DNS
    // already says mta1.tits.guru.
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $env = mailIdentityDnsHost($scratch, [
            ...mailIdentityGoodDns(mailIdentityPublicKey($key)),
            '@default PTR 10.113.0.203.in-addr.arpa' => ['contabo-eu-203.0.113.10.', 'contabo-eu-203.'],
        ]);

        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], $env);

        expect($run['status'])->toBe(0, $run['stdout'].$run['stderr']);
        expect($run['stdout'])
            ->toContain('PASS   ptr        203.0.113.10 PTR is mta1.tits.guru')
            ->toContain('DNS VERIFIED: YES')
            ->not->toContain('contabo');

        // Every query went to a public resolver by address; none reached the
        // host's own.
        $queries = mailIdentityDnsQueries($scratch);
        expect($queries)->toHaveCount(10);
        foreach ($queries as $query) {
            expect($query)->toMatch('/^(1\.1\.1\.1|8\.8\.8\.8) /');
        }

        // The control: the stale answer is really there for anything that asks
        // the host's resolver. The same run through a dig that drops the server
        // it is given — what code that never named one does — fails on exactly
        // the PTR, the way the production host did.
        @unlink($scratch.'/dns/queries.log');
        $local = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], [...$env, 'STUB_DIG_IGNORES_SERVER' => '1']);

        expect($local['status'])->not->toBe(0);
        expect($local['stdout'])
            ->toContain('FAIL   ptr        203.0.113.10 has 2 PTR records [contabo-eu-203. contabo-eu-203.0.113.10.]')
            ->toContain('DNS VERIFIED: NO');
        preg_match_all('/^  FAIL   (\S+)/m', $local['stdout'], $failures);
        expect($failures[1])->toBe(['ptr']);
        expect(mailIdentityDnsQueries($scratch))->toHaveCount(10)->each->toStartWith('default ');
    } finally {
        removeScratchDir($scratch);
    }
});

it('refuses a record unless both public resolvers answer it, and answer it the same way', function (array $changes, string $check, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $public = mailIdentityPublicKey($key);
        $dns = mailIdentityGoodDns($public);

        // The same rewriting as above, applied to one resolver's own answer:
        // FLIPPED_KEY is the installed key's public half with the case of one
        // letter changed.
        $flipped = preg_replace_callback('/[a-z]/', static fn (array $m): string => strtoupper($m[0]), $public, 1);
        foreach ($changes as $question => $answer) {
            $dns[$question] = array_map(
                static fn (mixed $value): mixed => is_string($value) ? str_replace('FLIPPED_KEY', $flipped, $value) : $value,
                $answer,
            );
        }

        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, $dns));

        expect($run['status'])->not->toBe(0, $run['stdout']);
        expect($run['stdout'])
            ->toMatch('/^  FAIL   '.preg_quote($check, '/').' +'.preg_quote($reason, '/').'/m')
            ->toContain('DNS VERIFIED: NO')
            ->not->toContain('DNS VERIFIED: YES');

        // Exactly the record the resolvers could not agree on fails; the four
        // they agree on still pass on their merits.
        preg_match_all('/^  FAIL   (\S+)/m', $run['stdout'], $failures);
        expect($failures[1])->toBe([$check]);

        // A disagreement over TXT never prints the values: a DKIM value is a key.
        expect($run['stdout'])->not->toContain('include:old.example')->not->toContain($flipped);
        expectNoKeyMaterial($run['stdout'].$run['stderr'], $key);
    } finally {
        removeScratchDir($scratch);
    }
})->with([
    'Cloudflare and Google name different PTRs' => [
        ['@8.8.8.8 PTR 10.113.0.203.in-addr.arpa' => ['other.example.']],
        'ptr',
        'public resolvers disagree on PTR 10.113.0.203.in-addr.arpa: 1.1.1.1 answers NOERROR [mta1.tits.guru.], 8.8.8.8 answers NOERROR [other.example.] — no answer is accepted until they all give the same one',
    ],
    'one resolver says the PTR does not exist' => [
        ['@1.1.1.1 PTR 10.113.0.203.in-addr.arpa' => ['status' => 'NXDOMAIN']],
        'ptr',
        'public resolvers disagree on PTR 10.113.0.203.in-addr.arpa: 1.1.1.1 answers NXDOMAIN with no PTR record, 8.8.8.8 answers NOERROR [mta1.tits.guru.]',
    ],
    'one resolver has the name but no A record' => [
        ['@8.8.8.8 A mta1.tits.guru' => ['status' => 'NOERROR']],
        'a',
        'public resolvers disagree on A mta1.tits.guru: 1.1.1.1 answers NOERROR [203.0.113.10], 8.8.8.8 answers NOERROR with no A record',
    ],
    'one resolver still has an old A record' => [
        ['@1.1.1.1 A mta1.tits.guru' => ['198.51.100.9']],
        'a',
        'public resolvers disagree on A mta1.tits.guru: 1.1.1.1 answers NOERROR [198.51.100.9], 8.8.8.8 answers NOERROR [203.0.113.10]',
    ],
    'one resolver times out' => [
        ['@8.8.8.8 A mta1.tits.guru' => ['exit' => 9]],
        'a',
        'the DNS query for A mta1.tits.guru to public resolver 8.8.8.8 failed (dig exit 9) — public DNS is only what 1.1.1.1 and 8.8.8.8 both answer, so no answer from fewer of them is accepted',
    ],
    'one resolver fails on the server' => [
        ['@1.1.1.1 TXT _dmarc.tits.guru' => ['status' => 'SERVFAIL']],
        'dmarc',
        'the DNS query for TXT _dmarc.tits.guru to public resolver 1.1.1.1 was answered SERVFAIL — public DNS is only what',
    ],
    'one resolver refuses' => [
        ['@8.8.8.8 TXT rg1._domainkey.tits.guru' => ['status' => 'REFUSED']],
        'dkim',
        'the DNS query for TXT rg1._domainkey.tits.guru to public resolver 8.8.8.8 was answered REFUSED — public DNS is only what',
    ],
    'one resolver still sees a second, older SPF policy' => [
        ['@8.8.8.8 TXT tits.guru' => ['"v=spf1 ip4:203.0.113.10 -all"', '"v=spf1 include:old.example ~all"', '"site-verification=abc123"']],
        'spf',
        'public resolvers disagree on TXT tits.guru: 1.1.1.1 answers NOERROR with 2 TXT record(s), 8.8.8.8 answers NOERROR with 3 TXT record(s) — no answer is accepted until they all give the same one (TXT values are not printed here; compare them with: dig @1.1.1.1 TXT tits.guru, dig @8.8.8.8 TXT tits.guru)',
    ],
    'DKIM keys that differ only in the case of one letter' => [
        ['@1.1.1.1 TXT rg1._domainkey.tits.guru' => ['"v=DKIM1; k=rsa; p=FLIPPED_KEY"']],
        'dkim',
        'public resolvers disagree on TXT rg1._domainkey.tits.guru: 1.1.1.1 answers NOERROR with 1 TXT record(s), 8.8.8.8 answers NOERROR with 1 TXT record(s)',
    ],
]);

it('never takes one public resolver\'s answers as enough while the other cannot be reached', function (string $unreachable, string $reachable) {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, [
            ...mailIdentityGoodDns(mailIdentityPublicKey($key)),
            "@{$unreachable} *" => ['exit' => 9],
        ]));

        expect($run['status'])->not->toBe(0);
        expect($run['stdout'])->toContain('DNS VERIFIED: NO');

        // Every record fails on the resolver that could not be reached, though
        // the other answered each of them correctly.
        preg_match_all('/^  FAIL   (\S+) +(.*)$/m', $run['stdout'], $failures);
        expect($failures[1])->toBe(['a', 'ptr', 'spf', 'dkim', 'dmarc']);
        foreach ($failures[2] as $detail) {
            expect($detail)
                ->toContain("to public resolver {$unreachable} failed (dig exit 9)")
                ->not->toContain("to public resolver {$reachable}");
        }

        expect(array_filter(mailIdentityDnsQueries($scratch), static fn (string $q): bool => str_starts_with($q, "{$reachable} ")))->toHaveCount(5);
    } finally {
        removeScratchDir($scratch);
    }
})->with([
    'Cloudflare unreachable' => ['1.1.1.1', '8.8.8.8'],
    'Google unreachable' => ['8.8.8.8', '1.1.1.1'],
]);

it('agrees on the same records whatever order each resolver returns them in, and on names in any letter case', function () {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $dns = mailIdentityGoodDns(mailIdentityPublicKey($key));
        $dns['A mta1.tits.guru'] = ['203.0.113.10', '203.0.113.11'];

        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, [
            ...$dns,
            '@8.8.8.8 A mta1.tits.guru' => array_reverse($dns['A mta1.tits.guru']),
            '@8.8.8.8 TXT tits.guru' => array_reverse($dns['TXT tits.guru']),
            '@1.1.1.1 PTR 10.113.0.203.in-addr.arpa' => ['MTA1.Tits.Guru.'],
        ]));

        expect($run['status'])->toBe(0, $run['stdout'].$run['stderr']);
        expect($run['stdout'])
            ->toContain('PASS   a          mta1.tits.guru A includes this host\'s address 203.0.113.10')
            ->toContain('PASS   ptr        203.0.113.10 PTR is mta1.tits.guru')
            ->toContain('PASS   spf')
            ->toContain('DNS VERIFIED: YES')
            ->not->toContain('disagree');
    } finally {
        removeScratchDir($scratch);
    }
});

it('judges the agreed answer by the same rules: a record both resolvers serve wrongly still fails', function () {
    // The consensus decides what public DNS says, never whether it is right:
    // two SPF policies served identically by both are still two.
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $dns = mailIdentityGoodDns(mailIdentityPublicKey($key));
        $dns['TXT tits.guru'] = ['"v=spf1 ip4:203.0.113.10 -all"', '"V=SPF1  ip4:203.0.113.10 -all"'];

        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, [
            ...$dns,
            '@8.8.8.8 TXT tits.guru' => array_reverse($dns['TXT tits.guru']),
        ]));

        expect($run['status'])->not->toBe(0);
        expect($run['stdout'])
            ->toContain('FAIL   spf        tits.guru publishes 2 SPF policies')
            ->not->toContain('disagree');
    } finally {
        removeScratchDir($scratch);
    }
});

it('fixes its public resolvers in the implementation, with no way to choose another or to fall back to the host\'s', function () {
    $code = executableSourceLines(File::get(mailIdentityScript()));

    // The witnesses are a constant of the script.
    expect($code)->toContain('readonly -a PUBLIC_DNS_RESOLVERS=(1.1.1.1 8.8.8.8)');

    // dig runs in exactly one place (beside the check that it exists), and
    // there it is always given the resolver it asks.
    expect(preg_match_all('/(?<!command -v )"\$\{DIG_BIN\}"/', $code))->toBe(1);
    expect($code)->toContain('"${DIG_BIN}" "@${resolver}" +nosearch ');

    // The only overrides are the gated test seams, and none of them names a
    // resolver.
    preg_match_all('/RATEGURU_MAILIDENTITY_[A-Z_]+/', $code, $overrides);
    expect(array_values(array_unique($overrides[0])))->toBe([
        'RATEGURU_MAILIDENTITY_FS_ROOT',
        'RATEGURU_MAILIDENTITY_DIG_BIN',
        'RATEGURU_MAILIDENTITY_IP_BIN',
        'RATEGURU_MAILIDENTITY_OPENSSL_BIN',
        'RATEGURU_MAILIDENTITY_SIGNING_VERIFIER_BIN',
    ]);

    // Nothing reads or changes the host's resolver configuration, and nothing
    // resolves a name any other way.
    foreach (['/etc/hosts', 'resolv.conf', '127.0.0.53', 'resolvectl', 'systemd-resolve', 'getent', 'nslookup', '+trace', '+norecurse', 'flush'] as $forbidden) {
        expect(str_contains($code, $forbidden))->toBeFalse("mail-identity uses {$forbidden}");
    }

    // An operator cannot name another resolver, on the command line or through
    // the environment.
    expectMailIdentityRefusal(
        mailIdentityRun(['verify-dns', '--target', 'tits-guru', '--resolver', '9.9.9.9']),
        'unknown argument: --resolver',
    );

    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $env = mailIdentityDnsHost($scratch, mailIdentityGoodDns(mailIdentityPublicKey($key)));

        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], [
            ...$env,
            'RATEGURU_MAILIDENTITY_RESOLVERS' => '9.9.9.9',
            'RATEGURU_MAILIDENTITY_PUBLIC_DNS_RESOLVERS' => '9.9.9.9',
            'PUBLIC_DNS_RESOLVERS' => '9.9.9.9',
        ]);

        expect($run['status'])->toBe(0, $run['stdout'].$run['stderr']);
        expect(array_values(array_unique(array_map(static fn (string $q): string => strtok($q, ' '), mailIdentityDnsQueries($scratch)))))
            ->toBe(['1.1.1.1', '8.8.8.8']);
    } finally {
        removeScratchDir($scratch);
    }

    // The usage an operator reads names the same two.
    expect(mailIdentityRun(['--help'])['stdout'])->toContain('public resolvers 1.1.1.1 and')->toContain('8.8.8.8 directly');
});

// =============================================================================
// THE SIGNING PLAN: WHAT THE HOST'S SIGNER SIGNS
// =============================================================================

it('renders the real signing plan: tits-guru, held, signed as tits.guru with rg1', function () {
    $run = mailIdentityRun(['render-signing-plan']);

    expect($run['status'])->toBe(0, $run['stderr']);
    expect(json_decode($run['stdout'], true, 512, JSON_THROW_ON_ERROR))->toBe([
        'schema_version' => 1,
        'targets' => [[
            'algorithm' => 'rsa-sha256',
            'domain' => 'tits.guru',
            'key_path' => '/etc/opendkim/keys/tits-guru/rg1.private',
            'key_requirement' => 'deferred',
            'minimum_key_bits' => 2048,
            'selector' => 'rg1',
            'target' => 'tits-guru',
        ]],
    ]);

    // Canonical: the same plan, byte for byte, every time.
    expect(mailIdentityRun(['render-signing-plan'])['stdout'])->toBe($run['stdout']);
});

it('plans every production identity, held ones included, and never a staging target', function () {
    $scratch = mailIdentityScratch();

    try {
        $plan = static fn (array $files): array => json_decode(mailIdentityRun(['render-signing-plan', ...$files])['stdout'], true, 512, JSON_THROW_ON_ERROR);

        // demo-shop held: planned, its key deferred.
        $held = $plan(mailIdentityFixtureConfig($scratch.'/config'));
        expect(collect($held['targets'])->pluck('target')->all())->toBe(['demo-shop', 'tits-guru']);
        expect(collect($held['targets'])->firstWhere('target', 'demo-shop'))->toBe([
            'algorithm' => 'rsa-sha256',
            'domain' => 'demo-shop.example',
            'key_path' => '/etc/opendkim/keys/demo-shop/shop2026.private',
            'key_requirement' => 'deferred',
            'minimum_key_bits' => 2048,
            'selector' => 'shop2026',
            'target' => 'demo-shop',
        ]);

        // demo-shop outbound: its key is required from now on.
        $outbound = $plan(mailIdentityFixtureConfig($scratch.'/config', [
            'mode' => 'outbound',
            'outbound' => ['schema_version' => 1, 'direct' => ['enabled' => true, 'mta_hostname' => 'mta1.example.net']],
        ]));
        expect(collect($outbound['targets'])->firstWhere('target', 'demo-shop')['key_requirement'])->toBe('required');

        // staging-main captures its mail and never signs it.
        foreach ([$held, $outbound] as $each) {
            expect(collect($each['targets'])->pluck('target')->all())->not->toContain('staging-main');
        }
    } finally {
        removeScratchDir($scratch);
    }
});

it('derives every value of the plan from its one authority, never from the caller', function () {
    $scratch = mailIdentityScratch();

    try {
        // A different selector and minimum in mail-identity.json, and a
        // different mail domain in mail-routing.json, reach the plan unchanged.
        $identity = mailIdentityDemoShopIdentity();
        $identity['dkim']['selector'] = 'brand7';
        $identity['dkim']['minimum_key_bits'] = 3072;
        $files = mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity]);

        $routing = json_decode((string) file_get_contents($scratch.'/config/mail-routing.json'), true);
        $routing['targets']['demo-shop']['mail_domain'] = 'books.demo-shop.example';
        $routing['targets']['demo-shop']['default_from'] = 'hello@books.demo-shop.example';
        $routing['targets']['demo-shop']['bounce_domain'] = 'bounce.books.demo-shop.example';
        $routing['targets']['demo-shop']['reply_domain'] = 'reply.books.demo-shop.example';
        file_put_contents($scratch.'/config/mail-routing.json', mailRoutingJson($routing));

        $run = mailIdentityRun(['render-signing-plan', ...$files]);
        expect($run['status'])->toBe(0, $run['stderr']);

        $entry = collect(json_decode($run['stdout'], true)['targets'])->firstWhere('target', 'demo-shop');
        expect($entry['domain'])->toBe('books.demo-shop.example');
        expect($entry['selector'])->toBe('brand7');
        expect($entry['minimum_key_bits'])->toBe(3072);
        expect($entry['key_path'])->toBe('/etc/opendkim/keys/demo-shop/brand7.private');

        // The key path is the same derivation dkim-key answers with.
        expect(mailIdentityRun(['dkim-key', '--target', 'demo-shop', ...$files])['stdout'])
            ->toBe("deferred\t/etc/opendkim/keys/demo-shop/brand7.private\t3072\n");

        // Nothing about a target can be chosen on the command line.
        foreach ([['--target', 'demo-shop'], ['--key', '/tmp/k'], ['--file', '/tmp/k'], ['--json']] as $option) {
            expectMailIdentityRefusal(mailIdentityRun(['render-signing-plan', ...$option]), "{$option[0]} is not an option of render-signing-plan");
        }
    } finally {
        removeScratchDir($scratch);
    }
});

it('renders no signing plan from contracts it refuses', function (string $file, string $document, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config');
        file_put_contents($scratch."/config/{$file}", $document);

        expectMailIdentityRefusal(mailIdentityRun(['render-signing-plan', ...$files]), $reason);
    } finally {
        removeScratchDir($scratch);
    }
})->with([
    'a malformed identity' => ['mail-identity.json', '{"schema_version": 1, "targets": {"tits-guru": {"dkim": {"selector": "RG1"}}}}', 'the mail identity contract refuses this'],
    'an identity that is not JSON' => ['mail-identity.json', '{"schema_version": 1,', 'the mail identity contract is not valid JSON'],
    'a malformed routing policy' => ['mail-routing.json', '{"schema_version": 2, "targets": {"tits-guru": {"delivery_mode": "teleport"}}}', 'mail-routing render-plan refused the routing policy'],
]);

it('prints an empty signing plan when no production target has a reviewed identity', function () {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config', ['demo-shop' => false]);
        file_put_contents($scratch.'/config/mail-identity.json', '{"schema_version": 1, "targets": {}}');

        $run = mailIdentityRun(['render-signing-plan', ...$files]);
        expect($run['status'])->toBe(0, $run['stderr']);
        expect(json_decode($run['stdout'], true))->toBe(['schema_version' => 1, 'targets' => []]);
    } finally {
        removeScratchDir($scratch);
    }
});

// =============================================================================
// READINESS: WHAT OUTBOUND DELIVERY WILL REQUIRE
// =============================================================================

it('reports every outbound condition for the real target, and none of them is met while it is held', function () {
    $scratch = mailIdentityScratch();

    try {
        $run = mailIdentityRun(['readiness', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, []));

        expect($run['status'])->not->toBe(0);
        expect($run['stdout'])
            ->toContain('PASS   target     environment_class production')
            ->toContain('FAIL   routing    delivery_mode held in mail-routing.json — not outbound')
            ->toContain('FAIL   direct     direct delivery is disabled on this host')
            ->toContain('PASS   mta        the reviewed public MTA hostname is mta1.tits.guru')
            ->toContain('FAIL   key        /etc/opendkim/keys/tits-guru/rg1.private is not usable: it does not exist')
            ->toContain('FAIL   signing    verify-mail-signing --read-only --target tits-guru did not pass (exit 1)')
            ->toContain('| ')
            ->toContain('OUTBOUND READY: NO')
            ->not->toContain('OUTBOUND READY: YES')
            ->not->toContain('no DKIM signing service is installed and verified on this host');

        // The signing condition is the verifier's verdict, asked read-only.
        expect(mailIdentitySigningCalls($scratch))->toBe(['--read-only --target tits-guru']);
    } finally {
        removeScratchDir($scratch);
    }
});

it('takes the signing condition from the signing verifier: PASS only when it passes', function () {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $env = mailIdentityDnsHost($scratch, mailIdentityGoodDns(mailIdentityPublicKey($key)));
        $failures = static function (string $stdout): array {
            preg_match_all('/^  FAIL   (\S+)/m', $stdout, $matches);

            return $matches[1];
        };

        // The accepted production state once the signer is installed: every
        // identity, key, DNS and signing condition holds, and the two gates
        // that keep the target held and the host without a direct route still
        // fail, each on its own.
        mailIdentitySigningVerdict($scratch, true);
        $run = mailIdentityRun(['readiness', '--target', 'tits-guru'], $env);

        expect($run['status'])->not->toBe(0);
        expect($failures($run['stdout']))->toBe(['routing', 'direct']);
        expect($run['stdout'])
            ->toContain('PASS   signing    verify-mail-signing --read-only --target tits-guru: the signing service, its access to the key and the gateway\'s wiring of this target are verified')
            ->toContain('PASS   key        /etc/opendkim/keys/tits-guru/rg1.private is a usable 2048-bit RSA private key')
            ->toContain('PASS   ptr        203.0.113.10 PTR is mta1.tits.guru')
            ->toContain('OUTBOUND READY: NO');

        // The verifier refusing is a FAIL — and only that changes.
        mailIdentitySigningVerdict($scratch, false);
        $run = mailIdentityRun(['readiness', '--target', 'tits-guru'], $env);

        expect($failures($run['stdout']))->toBe(['routing', 'direct', 'signing']);
        expect($run['stdout'])
            ->toContain('FAIL   signing    verify-mail-signing --read-only --target tits-guru did not pass (exit 1)')
            ->toContain('             |   FAIL the signer: install-mail-signing --verify --target tits-guru (exit 1)');

        // A verifier that cannot run at all is a FAIL too, never a pass.
        $run = mailIdentityRun(['readiness', '--target', 'tits-guru'], [...$env, 'RATEGURU_MAILIDENTITY_SIGNING_VERIFIER_BIN' => $scratch.'/bin/absent']);
        expect($run['stdout'])->toContain('FAIL   signing    the signing verifier is not executable');
        expectNoKeyMaterial($run['stdout'].$run['stderr'], $key);
    } finally {
        removeScratchDir($scratch);
    }
});

it('is outbound-ready only when every condition holds, the signer included', function () {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config', [
            'mode' => 'outbound',
            'outbound' => ['schema_version' => 1, 'direct' => ['enabled' => true, 'mta_hostname' => 'mta1.example.net']],
        ]);
        $key = mailIdentityInstallKey($scratch, 'demo-shop', 'shop2026');
        $env = mailIdentityDnsHost($scratch, mailIdentityGoodDns(mailIdentityPublicKey($key), '203.0.113.10', 'demo-shop.example', 'shop2026', 'mta1.example.net'));

        // Without a verified signer, exactly that condition fails.
        $run = mailIdentityRun(['readiness', '--target', 'demo-shop', ...$files], $env);

        expect($run['status'])->not->toBe(0);
        preg_match_all('/^  FAIL   (\S+)/m', $run['stdout'], $failures);
        expect($failures[1])->toBe(['signing']);
        expect($run['stdout'])
            ->toContain('PASS   routing    delivery_mode outbound')
            ->toContain('PASS   direct     direct delivery is enabled on this host as mta1.example.net')
            ->toContain('PASS   key        /etc/opendkim/keys/demo-shop/shop2026.private is a usable 2048-bit RSA private key')
            ->toContain('PASS   dkim')
            ->toContain('OUTBOUND READY: NO');

        // With it, the target is ready — the one state readiness was waiting for.
        mailIdentitySigningVerdict($scratch, true);
        $ready = mailIdentityRun(['readiness', '--target', 'demo-shop', ...$files], $env);

        expect($ready['status'])->toBe(0, $ready['stdout']);
        expect($ready['stdout'])->toContain('PASS   signing')->toContain('OUTBOUND READY: YES')->not->toContain('FAIL ');
        expect(mailIdentitySigningCalls($scratch))->toBe(['--read-only --target demo-shop', '--read-only --target demo-shop']);

        // And without its key, the target is not ready on that count as well.
        unlink($key);
        $missing = mailIdentityRun(['readiness', '--target', 'demo-shop', ...$files], mailIdentityDnsHost($scratch, []));
        expect($missing['stdout'])->toContain('FAIL   key        /etc/opendkim/keys/demo-shop/shop2026.private is not usable: it does not exist');
    } finally {
        removeScratchDir($scratch);
    }
});

it('never asks the signer of a target without a reviewed identity, and fails its signing condition', function () {
    $scratch = mailIdentityScratch();

    try {
        mailIdentitySigningVerdict($scratch, true);
        $run = mailIdentityRun(['readiness', '--target', 'staging-main'], mailIdentityDnsHost($scratch, []));

        expect($run['stdout'])
            ->toContain('FAIL   identity   no reviewed DKIM and DMARC identity in mail-identity.json')
            ->toContain('FAIL   signing    staging-main has no reviewed signing identity, so nothing on this host signs its mail')
            ->toContain('OUTBOUND READY: NO');
        expect(mailIdentitySigningCalls($scratch))->toBe([]);
    } finally {
        removeScratchDir($scratch);
    }
});

it('cannot be pointed at another signing verifier without the test-override gate', function () {
    $verifier = static function (array $environment): string {
        $process = proc_open(
            ['bash', '-c', 'source "$1" && printf "%s" "${SIGNING_VERIFIER}"', 'bash', mailIdentityScript()],
            [1 => ['pipe', 'w'], 2 => ['pipe', 'w']],
            $pipes,
            null,
            ['PATH' => getenv('PATH') ?: '/usr/bin:/bin', 'HOME' => sys_get_temp_dir(), ...$environment],
        );
        $stdout = (string) stream_get_contents($pipes[1]);
        stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        proc_close($process);

        return $stdout;
    };

    $own = base_path('infrastructure/scripts/verify-mail-signing');

    expect($verifier([]))->toBe($own);
    expect($verifier(['RATEGURU_MAILIDENTITY_SIGNING_VERIFIER_BIN' => '/tmp/always-passes']))->toBe($own);
    expect($verifier(['RATEGURU_MAILIDENTITY_SIGNING_VERIFIER_BIN' => '/tmp/always-passes', 'RATEGURU_ALLOW_TEST_OVERRIDES' => 'false']))->toBe($own);
    expect($verifier(['RATEGURU_MAILIDENTITY_SIGNING_VERIFIER_BIN' => '/tmp/always-passes', 'RATEGURU_ALLOW_TEST_OVERRIDES' => 'true']))->toBe('/tmp/always-passes');

    // And no option of readiness names a verifier.
    expectMailIdentityRefusal(
        mailIdentityRun(['readiness', '--target', 'tits-guru', '--verifier', '/tmp/always-passes']),
        'unknown argument: --verifier',
    );
});

it('asks the signing verifier read-only, and only that', function () {
    $code = executableSourceLines(File::get(mailIdentityScript()));

    expect($code)
        ->toContain('SIGNING_VERIFIER="$(gated_default RATEGURU_MAILIDENTITY_SIGNING_VERIFIER_BIN "${SCRIPT_DIR}/verify-mail-signing")"')
        ->toContain('"${SIGNING_VERIFIER}" --read-only --target "${TARGET_ID}"')
        ->not->toContain('--e2e')
        ->not->toContain('no DKIM signing service is installed and verified on this host');
    expect(substr_count($code, '"${SIGNING_VERIFIER}" --'))->toBe(1);
});

it('judges public DNS for readiness exactly as verify-dns does: both public resolvers, never the host\'s', function () {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config', [
            'mode' => 'outbound',
            'outbound' => ['schema_version' => 1, 'direct' => ['enabled' => true, 'mta_hostname' => 'mta1.example.net']],
        ]);
        $key = mailIdentityInstallKey($scratch, 'demo-shop', 'shop2026');
        $env = mailIdentityDnsHost($scratch, [
            ...mailIdentityGoodDns(mailIdentityPublicKey($key), '203.0.113.10', 'demo-shop.example', 'shop2026', 'mta1.example.net'),
            '@default PTR 10.113.0.203.in-addr.arpa' => ['stale.local.'],
            '@8.8.8.8 PTR 10.113.0.203.in-addr.arpa' => ['other.example.'],
        ]);

        $readiness = mailIdentityRun(['readiness', '--target', 'demo-shop', ...$files], $env);
        $readinessQueries = mailIdentityDnsQueries($scratch);
        @unlink($scratch.'/dns/queries.log');
        $verify = mailIdentityRun(['verify-dns', '--target', 'demo-shop', ...$files], $env);

        // The same disagreement, word for word, from both commands.
        $ptr = static fn (string $stdout): string => preg_match('/^  FAIL   ptr +(.*)$/m', $stdout, $m) ? $m[1] : '';
        expect($ptr($readiness['stdout']))->toStartWith('public resolvers disagree on PTR 10.113.0.203.in-addr.arpa: 1.1.1.1 answers NOERROR [mta1.example.net.], 8.8.8.8 answers NOERROR [other.example.]');
        expect($ptr($readiness['stdout']))->toBe($ptr($verify['stdout']));

        preg_match_all('/^  FAIL   (\S+)/m', $readiness['stdout'], $failures);
        expect($failures[1])->toBe(['ptr', 'signing']);
        expect($readiness['stdout'])->toContain('OUTBOUND READY: NO')->not->toContain('stale.local');

        // The same ten questions, to the same two resolvers.
        expect($readinessQueries)->toBe(mailIdentityDnsQueries($scratch))->toHaveCount(10);
        foreach ($readinessQueries as $query) {
            expect($query)->toMatch('/^(1\.1\.1\.1|8\.8\.8\.8) /');
        }
    } finally {
        removeScratchDir($scratch);
    }
});

// =============================================================================
// THE ROADMAP KEEPS THE REMAINING MAIL WORK APART
// =============================================================================

it('records the identity foundation and keeps the remaining mail work in its own slices', function () {
    $roadmap = preg_replace('/\s+/', ' ', File::get(base_path('infrastructure/ROADMAP.md')));

    expect($roadmap)
        ->toContain('**8.4B.4.1 Production mail identity foundation — IMPLEMENTED, nothing activated.**')
        ->toContain('**8.4B.4.1d Public DNS verified by independent public resolvers — IMPLEMENTED.**')
        ->toContain('**8.4B.4.2a DKIM signing foundation — PRODUCTION-ACCEPTED.**')
        ->toContain('**8.4B.4.2b Guarded outbound activation and the first real delivery — IMPLEMENTED — production activation pending.**')
        ->toContain('**8.4B.5 Bounce reception, reply routing and the support mailbox — planned.**')
        ->toContain('**8.4B.6 Suppression, delivery state and per-target metrics — planned.**')
        ->toContain('**8.4B.7 Mail operations, recovery and security acceptance — planned.**');
});
