<?php

use Illuminate\Support\Facades\File;

/**
 * infrastructure/scripts/mail-identity — the reviewed mail identity of the host
 * (mail-outbound.json) and of each production target (mail-identity.json): the
 * DKIM key a target signs with, the DNS records that publish it, and the proof,
 * from the host, that public DNS says exactly that.
 *
 * Every test runs the shipped script. Keys are real, generated by OpenSSL, and
 * the public key it derives is checked against PHP's own OpenSSL binding. DNS is
 * a stub that answers in the exact presentation format `dig` prints; nothing
 * here queries the network, and nothing anywhere sends mail.
 *
 * The real tits-guru identity is reviewed here, and stays inert: tits-guru is
 * still held and planned, and the host still has direct delivery disabled.
 */
/** A refusal: non-zero, and this reason on stderr. */
function expectMailIdentityRefusal(array $run, string $reason): void
{
    expect($run['status'])->not->toBe(0, "expected a refusal for: {$reason}\n{$run['stdout']}");
    expect($run['stdout'])->toBe('', 'a refused run printed something on stdout');
    expect(str_contains($run['stderr'], $reason))->toBeTrue("refusal reason not found:\n  {$reason}\nstderr was:\n{$run['stderr']}");
}

// =============================================================================
// THE REVIEWED IDENTITY
// =============================================================================

it('validates the real host and target identity contracts', function () {
    $run = mailIdentityRun(['validate']);

    expect($run['status'])->toBe(0, $run['stderr']);
    expect($run['stdout'])->toContain('mail identity is valid');

    // mta1.tits.guru is the reviewed host identity, and direct delivery stays
    // disabled on the host.
    expect(json_decode(File::get(base_path('infrastructure/config/mail-outbound.json')), true))
        ->toBe(['schema_version' => 1, 'direct' => ['enabled' => false, 'mta_hostname' => 'mta1.tits.guru']]);

    // rg1, RSA-SHA256, 2048 bits; DMARC p=none with strict alignment, and no
    // report address anywhere.
    expect(json_decode(File::get(base_path('infrastructure/config/mail-identity.json')), true))->toBe([
        'schema_version' => 1,
        'targets' => [
            'tits-guru' => [
                'dkim' => ['selector' => 'rg1', 'algorithm' => 'rsa-sha256', 'minimum_key_bits' => 2048],
                'dmarc' => ['policy' => 'none', 'adkim' => 'strict', 'aspf' => 'strict'],
            ],
        ],
    ]);

    expect(File::get(base_path('infrastructure/config/mail-identity.json')))
        ->not->toContain('rua')
        ->not->toContain('@')
        ->not->toContain('mail_domain')
        ->not->toContain('tits.guru');
});

it('keeps the real target held and planned, and the host without an outbound route', function () {
    $registry = json_decode(File::get(base_path('infrastructure/config/deployment-targets.json')), true);
    $routing = json_decode(File::get(base_path('infrastructure/config/mail-routing.json')), true);

    expect($registry['targets']['tits-guru']['lifecycle'])->toBe('planned');
    expect($routing['targets']['tits-guru']['delivery_mode'])->toBe('held');
    expect(json_decode(File::get(base_path('infrastructure/config/mail-outbound.json')), true)['direct']['enabled'])->toBeFalse();

    // The production environment is not touched by an identity.
    foreach (['production.env.example', 'tits-guru.env.example'] as $template) {
        $values = envFileValues("infrastructure/templates/environment/{$template}");

        foreach (['MAIL_MAILER', 'MAIL_HOST', 'MAIL_PORT', 'MAIL_FROM_ADDRESS'] as $key) {
            expect($values[$key] ?? '')->toBe('', "{$template} sets {$key}");
        }
    }
});

it('derives tits-guru\'s key destination from its ID and reviewed selector, deferred while its mail is held', function () {
    $run = mailIdentityRun(['dkim-key', '--target', 'tits-guru']);

    expect($run['status'])->toBe(0, $run['stderr']);
    expect($run['stdout'])->toBe("deferred\t/etc/opendkim/keys/tits-guru/rg1.private\t2048\n");

    // A target with no production identity has no key at all.
    expect(mailIdentityRun(['dkim-key', '--target', 'staging-main'])['stdout'])->toBe("none\n");
});

it('derives a target it has never heard of the same way, and requires its key once it is outbound', function () {
    $scratch = mailIdentityScratch();

    try {
        $held = mailIdentityRun(['dkim-key', '--target', 'demo-shop', ...mailIdentityFixtureConfig($scratch.'/config')]);
        expect($held['stdout'])->toBe("deferred\t/etc/opendkim/keys/demo-shop/shop2026.private\t2048\n");

        $outbound = mailIdentityRun(['dkim-key', '--target', 'demo-shop', ...mailIdentityFixtureConfig($scratch.'/config', [
            'mode' => 'outbound',
            'outbound' => ['schema_version' => 1, 'direct' => ['enabled' => true, 'mta_hostname' => 'mta1.example.net']],
        ])]);
        expect($outbound['stdout'])->toBe("required\t/etc/opendkim/keys/demo-shop/shop2026.private\t2048\n");
    } finally {
        mailIdentityCleanup($scratch);
    }
});

it('names no target, domain, selector or host anywhere in its implementation', function () {
    $source = File::get(mailIdentityScript());

    foreach (['tits-guru', 'tits.guru', 'rg1', 'mta1', 'demo-shop', 'staging-main', 'staging.invalid', '203.0.113'] as $name) {
        expect(str_contains($source, $name))->toBeFalse("mail-identity names {$name}");
    }

    // The policy reaches it only through mail-routing's render, and nothing from
    // a contract is ever evaluated as code.
    $code = executableSourceLines($source);
    expect($code)
        ->toContain('"${MAIL_ROUTING_CLI}" render-plan --file "${ROUTING_FILE}" --registry "${REGISTRY_FILE}"')
        ->not->toContain('eval ')
        ->not->toContain('bash -c');
});

it('changes nothing: no file, no service, no record, no mail', function () {
    $code = executableSourceLines(File::get(mailIdentityScript()));

    // Commands, as whole words: "-outform" is not rm, and "installed" in a
    // message is not install.
    foreach (['install', 'mkdir', 'chmod', 'chown', 'mv', 'rm', 'tee', 'cp', 'mktemp', 'systemctl', 'postconf', 'postfix', 'postsuper', 'sendmail', 'nsupdate', 'curl', 'wget', 'ssh', 'scp', 'sudo', 'genpkey', 'genrsa', 'req'] as $command) {
        expect(preg_match('/(?<![\w-])'.preg_quote($command, '/').'(?![\w-])/', $code))->toBe(0, "mail-identity runs {$command}");
    }

    // A key is never printed in any form: no text dump, no cat, no echo of it.
    foreach (['-text -in', 'cat "${path}"', 'cat "$1"', '-noout -text -in'] as $leak) {
        expect(str_contains($code, $leak))->toBeFalse("mail-identity could print a key with {$leak}");
    }
});

it('is repository tooling, never installed onto a host', function () {
    expect(repositoryOnlyScriptNames())->toContain('mail-identity');
    expect(requiredCliManifestNames())->not->toContain('mail-identity');
    expect(executableSourceLines(File::get(base_path('infrastructure/scripts/install-target-operations'))))
        ->not->toContain('mail-identity');
});

// =============================================================================
// THE IDENTITY CONTRACT IS CLOSED
// =============================================================================

it('refuses an identity whose target the registry does not have, or that is not a production one', function (array $identity, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config');
        $document = json_decode((string) file_get_contents($scratch.'/config/mail-identity.json'), true);
        $document['targets'] = [...$document['targets'], ...$identity];
        file_put_contents($scratch.'/config/mail-identity.json', mailRoutingJson($document));

        expectMailIdentityRefusal(mailIdentityRun(['validate', ...$files]), $reason);
    } finally {
        mailIdentityCleanup($scratch);
    }
})->with([
    'an unknown target' => [['food-guru' => mailIdentityDemoShopIdentity()], 'food-guru: not a target in the deployment registry'],
    'a staging target' => [['staging-main' => mailIdentityDemoShopIdentity()], 'staging-main: environment_class staging has no production mail identity — a staging target captures its mail and never signs it'],
    'a malformed target ID' => [['Demo_Shop' => mailIdentityDemoShopIdentity()], 'invalid target ID "Demo_Shop"'],
]);

it('refuses a DKIM selector that is not one safe lowercase DNS label', function (mixed $selector) {
    $scratch = mailIdentityScratch();

    try {
        $identity = mailIdentityDemoShopIdentity();
        $identity['dkim']['selector'] = $selector;

        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity])]),
            'demo-shop: dkim.selector must be one lowercase DNS label',
        );
    } finally {
        mailIdentityCleanup($scratch);
    }
})->with([
    'uppercase' => 'RG1',
    'two labels' => 'rg1.mail',
    'an underscore' => 'rg_1',
    'a leading hyphen' => '-rg1',
    'a trailing hyphen' => 'rg1-',
    'empty' => '',
    'longer than a label' => str_repeat('a', 64),
    'whitespace' => 'rg 1',
    'a number' => 1,
]);

it('accepts exactly rsa-sha256 as the DKIM algorithm', function (mixed $algorithm) {
    $scratch = mailIdentityScratch();

    try {
        $identity = mailIdentityDemoShopIdentity();
        $identity['dkim']['algorithm'] = $algorithm;

        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity])]),
            'demo-shop: dkim.algorithm must be one of rsa-sha256, got '.json_encode($algorithm),
        );
    } finally {
        mailIdentityCleanup($scratch);
    }
})->with(['rsa-sha1', 'ed25519-sha256', 'RSA-SHA256', 'rsa', '']);

it('refuses a minimum key size below 2048 bits, or one that is not a whole number of bits', function (mixed $bits) {
    $scratch = mailIdentityScratch();

    try {
        $identity = mailIdentityDemoShopIdentity();
        $identity['dkim']['minimum_key_bits'] = $bits;

        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity])]),
            'demo-shop: dkim.minimum_key_bits must be an integer from 2048 to 4096',
        );
    } finally {
        mailIdentityCleanup($scratch);
    }
})->with([1024, 2047, 0, -2048, 2048.5, '2048', 8192, null]);

it('accepts every reviewed key size from 2048 to 4096 bits', function (int $bits) {
    $scratch = mailIdentityScratch();

    try {
        $identity = mailIdentityDemoShopIdentity();
        $identity['dkim']['minimum_key_bits'] = $bits;

        $run = mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity])]);
        expect($run['status'])->toBe(0, $run['stderr']);
    } finally {
        mailIdentityCleanup($scratch);
    }
})->with([2048, 3072, 4096]);

it('refuses a DMARC policy outside the reviewed vocabulary', function (array $dmarc, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        $identity = mailIdentityDemoShopIdentity();
        $identity['dmarc'] = [...$identity['dmarc'], ...$dmarc];

        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => $identity])]),
            $reason,
        );
    } finally {
        mailIdentityCleanup($scratch);
    }
})->with([
    'an unknown policy' => [['policy' => 'monitor'], 'demo-shop: dmarc.policy must be one of none, quarantine, reject, got "monitor"'],
    'a DNS tag value for alignment' => [['adkim' => 's'], 'demo-shop: dmarc.adkim must be one of relaxed, strict, got "s"'],
    'an empty alignment' => [['aspf' => ''], 'demo-shop: dmarc.aspf must be one of relaxed, strict, got ""'],
    'a report address nobody reviewed' => [['rua' => 'mailto:dmarc@demo-shop.example'], 'demo-shop: dmarc must be exactly {policy, adkim, aspf}, found ["adkim","aspf","policy","rua"]'],
]);

it('never repeats what mail-routing is the authority for, and holds no secret', function (array $set, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', ['identity' => [...mailIdentityDemoShopIdentity(), ...$set]])]),
            $reason,
        );
    } finally {
        mailIdentityCleanup($scratch);
    }
})->with([
    'the mail domain' => [['mail_domain' => 'demo-shop.example'], 'demo-shop: identity must be exactly {dkim, dmarc}, found ["dkim","dmarc","mail_domain"] — the mail domain, sender, bounce and reply domains stay in mail-routing.json'],
    'the sender' => [['default_from' => 'hello@demo-shop.example'], 'identity must be exactly {dkim, dmarc}'],
    'the submission port' => [['submission' => ['host' => '127.0.0.1', 'port' => 2599]], 'identity must be exactly {dkim, dmarc}'],
    'the delivery mode' => [['delivery_mode' => 'outbound'], 'identity must be exactly {dkim, dmarc}'],
    'a private key' => [['private_key' => 'MIIE...'], 'the identity contract holds a secret-like property name "private_key"'],
]);

it('refuses an outbound target that has no reviewed identity', function () {
    $scratch = mailIdentityScratch();

    try {
        expectMailIdentityRefusal(
            mailIdentityRun(['validate', ...mailIdentityFixtureConfig($scratch.'/config', [
                'mode' => 'outbound',
                'identity' => null,
                'outbound' => ['schema_version' => 1, 'direct' => ['enabled' => true, 'mta_hostname' => 'mta1.example.net']],
            ])]),
            'demo-shop: delivers outbound, so it needs a reviewed DKIM and DMARC identity in mail-identity.json',
        );
    } finally {
        mailIdentityCleanup($scratch);
    }
});

it('refuses an identity document that is not exactly one reviewed object', function (string $document, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config');
        file_put_contents($scratch.'/config/mail-identity.json', $document);

        expectMailIdentityRefusal(mailIdentityRun(['validate', ...$files]), $reason);
    } finally {
        mailIdentityCleanup($scratch);
    }
})->with([
    'another schema' => ['{"schema_version": 2, "targets": {}}', 'unsupported mail identity schema_version: 2 (expected 1)'],
    'not JSON' => ['{"schema_version": 1,', 'the mail identity contract is not valid JSON'],
    'a key declared twice' => ['{"schema_version": 1, "targets": {"tits-guru": {}, "tits-guru": {}}}', 'declares the same key twice in one object'],
    'an extra property' => ['{"schema_version": 1, "comment": "x", "targets": {}}', 'the mail identity contract must be exactly {schema_version, targets}'],
    'a control character' => ['{"schema_version": 1, "targets": {"tits-guru": {"dkim": {"selector": "rg1\\n"}}}}', 'must not contain control characters'],
]);

it('accepts a reviewed MTA hostname while direct delivery stays disabled, and judges it all the same', function () {
    $scratch = mailIdentityScratch();

    try {
        // The real shape: named and disabled.
        $files = mailIdentityFixtureConfig($scratch.'/config', ['outbound' => ['schema_version' => 1, 'direct' => ['enabled' => false, 'mta_hostname' => 'mta1.example.net']]]);
        expect(mailIdentityRun(['validate', ...$files])['status'])->toBe(0);

        // A disabled hostname is still a reviewed value, so it is still judged.
        $files = mailIdentityFixtureConfig($scratch.'/config', ['outbound' => ['schema_version' => 1, 'direct' => ['enabled' => false, 'mta_hostname' => 'mta1.rateguru.invalid']]]);
        expectMailIdentityRefusal(mailIdentityRun(['validate', ...$files]), 'direct.mta_hostname "mta1.rateguru.invalid" is under the reserved .invalid domain');
    } finally {
        mailIdentityCleanup($scratch);
    }
});

// =============================================================================
// PRIVATE KEYS: JUDGED, NEVER SHOWN
// =============================================================================

it('accepts an unencrypted RSA private key of at least the reviewed size, PKCS#8 or PKCS#1', function (string $kind, int $bits) {
    $run = mailIdentityRun(['check-key', '--file', mailIdentityKey($kind)]);

    expect($run['status'])->toBe(0, $run['stderr']);
    expect($run['stdout'])->toContain("usable: an unencrypted {$bits}-bit RSA private key");
    expectNoKeyMaterial($run['stdout'].$run['stderr'], mailIdentityKey($kind));
})->with([
    'PKCS#8, 2048 bits' => ['rsa2048', 2048],
    'PKCS#1, 2048 bits' => ['rsa2048-pkcs1', 2048],
    'PKCS#8, 3072 bits' => ['rsa3072', 3072],
]);

it('refuses everything that is not a usable DKIM private key, without ever showing it', function (string $kind, string $reason) {
    $run = mailIdentityRun(['check-key', '--file', mailIdentityKey($kind)]);

    expectMailIdentityRefusal($run, "not a usable DKIM private key: {$reason}");
    expectNoKeyMaterial($run['stdout'].$run['stderr'], mailIdentityKey($kind));
})->with([
    'not PEM at all' => ['junk', 'it is not PEM'],
    'a public key' => ['public', 'it is a public key, not a private key'],
    'a certificate' => ['certificate', 'it is a certificate, not a private key'],
    'a key with a certificate beside it' => ['key-and-certificate', 'it is a certificate, not a private key'],
    'a passphrase-protected key' => ['encrypted', 'it is passphrase-protected'],
    'RSA below 2048 bits' => ['rsa1024', 'it is a 1024-bit RSA key, below the reviewed minimum of 2048 bits'],
    'an EC key' => ['ec', 'it is not a usable RSA private key'],
    'an Ed25519 key' => ['ed25519', 'it is not a usable RSA private key'],
]);

it('holds a key to the minimum the identity reviews, not merely to 2048 bits', function () {
    expectMailIdentityRefusal(
        mailIdentityRun(['check-key', '--file', mailIdentityKey('rsa2048'), '--min-bits', '3072']),
        'it is a 2048-bit RSA key, below the reviewed minimum of 3072 bits',
    );
    expect(mailIdentityRun(['check-key', '--file', mailIdentityKey('rsa3072'), '--min-bits', '3072'])['status'])->toBe(0);
});

it('refuses a key reached through a symlink, or that is not a regular file', function () {
    $scratch = mailIdentityScratch();

    try {
        symlink(mailIdentityKey('rsa2048'), $scratch.'/link.pem');

        expectMailIdentityRefusal(mailIdentityRun(['check-key', '--file', $scratch.'/link.pem']), 'it is a symlink');
        expectMailIdentityRefusal(mailIdentityRun(['check-key', '--file', $scratch.'/fs']), 'it is not a regular file');
        expectMailIdentityRefusal(mailIdentityRun(['check-key', '--file', $scratch.'/absent.pem']), 'it does not exist');
    } finally {
        mailIdentityCleanup($scratch);
    }
});

// =============================================================================
// THE DNS TO PUBLISH
// =============================================================================

it('prints exactly the records to publish, deriving the DKIM public key from the installed private key', function () {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $env = mailIdentityDnsHost($scratch, []);

        $run = mailIdentityRun(['show-dns', '--target', 'tits-guru'], $env);
        expect($run['status'])->toBe(0, $run['stderr']);

        $text = preg_replace('/\s+/', ' ', $run['stdout']);
        $public = mailIdentityPublicKey($key);

        expect($text)
            ->toContain('hostname mta1.tits.guru (direct delivery disabled on this host)')
            ->toContain('A mta1.tits.guru -> 203.0.113.10')
            ->toContain('PTR 203.0.113.10 -> mta1.tits.guru')
            ->toContain('TXT rg1._domainkey.tits.guru v=DKIM1; k=rsa; p='.$public)
            ->toContain('TXT tits.guru v=spf1 ip4:203.0.113.10 -all')
            ->toContain('TXT _dmarc.tits.guru v=DMARC1; p=none; adkim=s; aspf=s');

        expectNoKeyMaterial($run['stdout'].$run['stderr'], $key);

        // Deterministic: the same key and host print the same plan.
        expect(mailIdentityRun(['show-dns', '--target', 'tits-guru'], $env)['stdout'])->toBe($run['stdout']);
    } finally {
        mailIdentityCleanup($scratch);
    }
});

it('prints the same records as JSON, with nothing but public values', function () {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $run = mailIdentityRun(['show-dns', '--target', 'tits-guru', '--json'], mailIdentityDnsHost($scratch, []));

        expect($run['status'])->toBe(0, $run['stderr']);
        $plan = json_decode($run['stdout'], true, 512, JSON_THROW_ON_ERROR);

        expect($plan['mta'])->toBe(['direct_delivery_enabled' => false, 'hostname' => 'mta1.tits.guru', 'ipv4' => '203.0.113.10']);
        expect($plan['records'])->toBe([
            ['name' => 'mta1.tits.guru', 'type' => 'A', 'value' => '203.0.113.10'],
            ['name' => '203.0.113.10', 'type' => 'PTR', 'value' => 'mta1.tits.guru'],
            ['name' => 'rg1._domainkey.tits.guru', 'type' => 'TXT', 'value' => 'v=DKIM1; k=rsa; p='.mailIdentityPublicKey($key)],
            ['name' => 'tits.guru', 'type' => 'TXT', 'value' => 'v=spf1 ip4:203.0.113.10 -all'],
            ['name' => '_dmarc.tits.guru', 'type' => 'TXT', 'value' => 'v=DMARC1; p=none; adkim=s; aspf=s'],
        ]);

        expectNoKeyMaterial($run['stdout'], $key);
    } finally {
        mailIdentityCleanup($scratch);
    }
});

it('derives the public key from a key the operator holds, before it is installed anywhere', function () {
    // The order an operator works in: create the key, publish its public half,
    // then supply it. show-dns reads a key file named on the command line and
    // still prints only the public half.
    $scratch = mailIdentityScratch();

    try {
        $run = mailIdentityRun(['show-dns', '--target', 'tits-guru', '--key', mailIdentityKey('rsa2048-pkcs1'), '--ipv4', '198.51.100.7']);

        expect($run['status'])->toBe(0, $run['stderr']);
        expect(preg_replace('/\s+/', ' ', $run['stdout']))
            ->toContain('p='.mailIdentityPublicKey(mailIdentityKey('rsa2048')))
            ->toContain('v=spf1 ip4:198.51.100.7 -all');
        expectNoKeyMaterial($run['stdout'].$run['stderr'], mailIdentityKey('rsa2048-pkcs1'));
    } finally {
        mailIdentityCleanup($scratch);
    }
});

it('says what is still pending instead of inventing a key or an address', function () {
    $scratch = mailIdentityScratch();

    try {
        $run = mailIdentityRun(['show-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, [], null));

        expect($run['status'])->toBe(0, $run['stderr']);
        expect($run['stdout'])
            ->toContain('<pending: the installed key /etc/opendkim/keys/tits-guru/rg1.private is not usable — it does not exist>')
            ->toContain('<this host IPv4: run on the mail host, or pass --ipv4>')
            ->not->toContain('v=DKIM1');

        // A weak key is named as such, and never published.
        mailIdentityInstallKey($scratch, 'tits-guru', 'rg1', 'rsa1024');
        expect(mailIdentityRun(['show-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, []))['stdout'])
            ->toContain('below the reviewed minimum of 2048 bits')
            ->not->toContain('v=DKIM1; k=rsa; p=');

        expectMailIdentityRefusal(mailIdentityRun(['show-dns', '--target', 'staging-main']), 'staging-main has no mail identity');
    } finally {
        mailIdentityCleanup($scratch);
    }
});

// =============================================================================
// VERIFYING PUBLIC DNS
// =============================================================================

it('verifies correctly published DNS, joining a long DKIM record a provider split into chunks', function () {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $dns = mailIdentityGoodDns(mailIdentityPublicKey($key));

        // Proof the record really is split, with whitespace between the chunks.
        expect(substr_count($dns['TXT rg1._domainkey.tits.guru'][0], '" "'))->toBeGreaterThan(0);

        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, $dns));

        expect($run['status'])->toBe(0, $run['stdout'].$run['stderr']);
        expect($run['stdout'])
            ->toContain('PASS   a          mta1.tits.guru A includes this host\'s address 203.0.113.10')
            ->toContain('PASS   ptr        203.0.113.10 PTR is mta1.tits.guru')
            ->toContain('PASS   spf        tits.guru SPF authorizes exactly this host (203.0.113.10) and fails everything else')
            ->toContain('PASS   dkim       rg1._domainkey.tits.guru publishes exactly the public key of the installed private key')
            ->toContain('PASS   dmarc      _dmarc.tits.guru publishes exactly the reviewed policy')
            ->toContain('DNS VERIFIED: YES');
        expectNoKeyMaterial($run['stdout'].$run['stderr'], $key);
    } finally {
        mailIdentityCleanup($scratch);
    }
});

it('accepts a DKIM value a DNS panel published with whitespace inside the key, as verifiers do', function () {
    // RFC 6376 lets the base64 in p= carry folding whitespace, and some DNS
    // panels insert spaces into a long value; a verifier ignores them.
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $dns = mailIdentityGoodDns(mailIdentityPublicKey($key));
        $dns['TXT rg1._domainkey.tits.guru'] = ['"v=DKIM1;  k=rsa ;  p='.implode(' ', str_split(mailIdentityPublicKey($key), 64)).'"'];

        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, $dns));

        expect($run['status'])->toBe(0, $run['stdout']);
        expect($run['stdout'])->toContain('PASS   dkim       rg1._domainkey.tits.guru publishes exactly the public key of the installed private key');
    } finally {
        mailIdentityCleanup($scratch);
    }
});

it('refuses every way public DNS can disagree with the reviewed identity', function (array $changes, string|false|null $ipv4, string $check, string $reason) {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $dns = mailIdentityGoodDns(mailIdentityPublicKey($key));

        // Each change replaces one answer whole; null removes it, and
        // OTHER_KEY stands for the public key of a different private key.
        foreach ($changes as $question => $answer) {
            if ($answer === null) {
                unset($dns[$question]);

                continue;
            }

            $dns[$question] = array_map(
                static fn (mixed $value): mixed => is_string($value) ? str_replace('OTHER_KEY', mailIdentityPublicKey(mailIdentityKey('rsa3072')), $value) : $value,
                $answer,
            );
        }

        $run = mailIdentityRun(
            ['verify-dns', '--target', 'tits-guru'],
            mailIdentityDnsHost($scratch, $dns, $ipv4 === false ? '203.0.113.10' : $ipv4),
        );

        expect($run['status'])->not->toBe(0, $run['stdout']);
        expect($run['stdout'])
            ->toMatch('/^  FAIL   '.preg_quote($check, '/').' +.*'.preg_quote($reason, '/').'/m')
            ->toContain('DNS VERIFIED: NO')
            ->not->toContain('DNS VERIFIED: YES');
        expectNoKeyMaterial($run['stdout'].$run['stderr'], $key);
    } finally {
        mailIdentityCleanup($scratch);
    }
})->with([
    'an A record elsewhere' => [['A mta1.tits.guru' => ['198.51.100.9']], false, 'a', 'mta1.tits.guru A is [198.51.100.9], which does not include this host\'s address 203.0.113.10'],
    'no A record' => [['A mta1.tits.guru' => null], false, 'a', 'mta1.tits.guru has no A record (NXDOMAIN)'],
    'a PTR naming something else' => [['PTR 10.113.0.203.in-addr.arpa' => ['ip-203-0-113-10.provider.example.']], false, 'ptr', '203.0.113.10 PTR is ip-203-0-113-10.provider.example, not mta1.tits.guru'],
    'no PTR' => [['PTR 10.113.0.203.in-addr.arpa' => null], false, 'ptr', '203.0.113.10 has no PTR record'],
    'two PTR records' => [['PTR 10.113.0.203.in-addr.arpa' => ['mta1.tits.guru.', 'other.example.']], false, 'ptr', 'has 2 PTR records'],
    'two SPF policies' => [['TXT tits.guru' => ['"v=spf1 ip4:203.0.113.10 -all"', '"v=spf1 include:_spf.provider.example ~all"']], false, 'spf', 'tits.guru publishes 2 SPF policies — receivers treat more than one as a permanent error'],
    'no SPF policy' => [['TXT tits.guru' => ['"site-verification=abc123"']], false, 'spf', 'tits.guru publishes no SPF policy — publish exactly one TXT record: v=spf1 ip4:203.0.113.10 -all'],
    'a soft-failing SPF' => [['TXT tits.guru' => ['"v=spf1 ip4:203.0.113.10 ~all"']], false, 'spf', 'tits.guru SPF is "v=spf1 ip4:203.0.113.10 ~all", not the reviewed'],
    'SPF for another address' => [['TXT tits.guru' => ['"v=spf1 ip4:198.51.100.9 -all"']], false, 'spf', 'not the reviewed "v=spf1 ip4:203.0.113.10 -all"'],
    'a DKIM record for another key' => [['TXT rg1._domainkey.tits.guru' => ['"v=DKIM1; k=rsa; p=OTHER_KEY"']], false, 'dkim', 'publishes a different public key than the installed private key derives'],
    'no DKIM record' => [['TXT rg1._domainkey.tits.guru' => null], false, 'dkim', 'rg1._domainkey.tits.guru has no TXT record'],
    'a DKIM record of another key type' => [['TXT rg1._domainkey.tits.guru' => ['"v=DKIM1; k=ed25519; p=abc"']], false, 'dkim', 'rg1._domainkey.tits.guru has k=ed25519, not k=rsa'],
    'a DKIM record in testing mode' => [['TXT rg1._domainkey.tits.guru' => ['"v=DKIM1; t=y; k=rsa; p=abc"']], false, 'dkim', 'must carry exactly the tags v, k and p, found: k p t v'],
    'two DKIM records' => [['TXT rg1._domainkey.tits.guru' => ['"v=DKIM1; k=rsa; p=OTHER_KEY"', '"v=DKIM1; k=rsa; p=abc"']], false, 'dkim', 'has 2 TXT records — a selector publishes exactly one key'],
    'a rejecting DMARC policy' => [['TXT _dmarc.tits.guru' => ['"v=DMARC1; p=reject; adkim=s; aspf=s"']], false, 'dmarc', '_dmarc.tits.guru has p=reject, not the reviewed p=none'],
    'relaxed DKIM alignment' => [['TXT _dmarc.tits.guru' => ['"v=DMARC1; p=none; adkim=r; aspf=s"']], false, 'dmarc', 'has adkim=r, not the reviewed adkim=s'],
    'a report address nobody reviewed' => [['TXT _dmarc.tits.guru' => ['"v=DMARC1; p=none; adkim=s; aspf=s; rua=mailto:x@tits.guru"']], false, 'dmarc', 'must carry exactly v, p, adkim and aspf'],
    'two DMARC policies' => [['TXT _dmarc.tits.guru' => ['"v=DMARC1; p=none; adkim=s; aspf=s"', '"v=DMARC1; p=none"']], false, 'dmarc', 'publishes 2 DMARC policies — exactly one is allowed'],
    'no DMARC policy' => [['TXT _dmarc.tits.guru' => null], false, 'dmarc', '_dmarc.tits.guru publishes no DMARC policy — publish exactly: v=DMARC1; p=none; adkim=s; aspf=s'],
    'a resolver that never answers' => [['TXT tits.guru' => ['exit' => 9]], false, 'spf', 'the DNS query for tits.guru TXT failed (dig exit 9)'],
    'a server failure' => [['TXT _dmarc.tits.guru' => ['status' => 'SERVFAIL']], false, 'dmarc', 'the DNS query for _dmarc.tits.guru TXT was answered SERVFAIL'],
    'a refused query' => [['A mta1.tits.guru' => ['status' => 'REFUSED']], false, 'a', 'was answered REFUSED'],
    'a host behind NAT' => [[], '10.0.0.5', 'address', 'this host sends from 10.0.0.5, which is not a public address'],
    'a host with no route' => [[], null, 'address', 'this host has no IPv4 route to the Internet'],
]);

it('cannot pass without a usable installed key, whatever DNS says', function () {
    $scratch = mailIdentityScratch();

    try {
        $dns = mailIdentityGoodDns(mailIdentityPublicKey(mailIdentityKey('rsa2048')));

        // Absent.
        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, $dns));
        expect($run['status'])->not->toBe(0);
        expect($run['stdout'])
            ->toContain('FAIL   key        the DKIM private key /etc/opendkim/keys/tits-guru/rg1.private is not usable: it does not exist')
            ->toContain('there is no valid installed private key to compare it with');

        // Too weak, even with a record that matches it.
        $weak = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1', 'rsa1024');
        $dns['TXT rg1._domainkey.tits.guru'] = ['"v=DKIM1; k=rsa; p='.mailIdentityPublicKey($weak).'"'];
        $run = mailIdentityRun(['verify-dns', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, $dns));
        expect($run['status'])->not->toBe(0);
        expect($run['stdout'])->toContain('below the reviewed minimum of 2048 bits')->toContain('DNS VERIFIED: NO');
    } finally {
        mailIdentityCleanup($scratch);
    }
});

it('verifies a target it has never heard of against its own domain, selector and the host\'s name', function () {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config', ['outbound' => ['schema_version' => 1, 'direct' => ['enabled' => false, 'mta_hostname' => 'mta1.example.net']]]);
        $key = mailIdentityInstallKey($scratch, 'demo-shop', 'shop2026', 'rsa3072');

        $run = mailIdentityRun(
            ['verify-dns', '--target', 'demo-shop', ...$files],
            mailIdentityDnsHost($scratch, mailIdentityGoodDns(mailIdentityPublicKey($key), '203.0.113.10', 'demo-shop.example', 'shop2026', 'mta1.example.net')),
        );

        expect($run['status'])->toBe(0, $run['stdout'].$run['stderr']);
        expect($run['stdout'])->toContain('shop2026._domainkey.demo-shop.example publishes exactly the public key')->toContain('DNS VERIFIED: YES');
    } finally {
        mailIdentityCleanup($scratch);
    }
});

it('only reads: verifying DNS writes nothing and asks DNS nothing but the five records', function () {
    $scratch = mailIdentityScratch();

    try {
        $key = mailIdentityInstallKey($scratch, 'tits-guru', 'rg1');
        $env = mailIdentityDnsHost($scratch, mailIdentityGoodDns(mailIdentityPublicKey($key)));

        $tree = static function () use ($scratch): array {
            $files = [];
            foreach (File::allFiles($scratch.'/fs', true) as $file) {
                $files[$file->getRelativePathname()] = [hash_file('sha256', $file->getPathname()), $file->getPerms()];
            }
            ksort($files);

            return $files;
        };

        $before = $tree();
        expect(mailIdentityRun(['verify-dns', '--target', 'tits-guru'], $env)['status'])->toBe(0);
        expect($tree())->toBe($before);

        expect(array_values(array_filter(explode("\n", (string) file_get_contents($scratch.'/dns/queries.log')))))->toBe([
            'A mta1.tits.guru',
            'PTR 10.113.0.203.in-addr.arpa',
            'TXT tits.guru',
            'TXT rg1._domainkey.tits.guru',
            'TXT _dmarc.tits.guru',
        ]);
    } finally {
        mailIdentityCleanup($scratch);
    }
});

// =============================================================================
// READINESS: WHAT OUTBOUND DELIVERY WILL REQUIRE
// =============================================================================

it('reports every outbound condition for the real target, and none of them is met while it is held', function () {
    $scratch = mailIdentityScratch();

    try {
        $run = mailIdentityRun(['readiness', '--target', 'tits-guru'], mailIdentityDnsHost($scratch, []));

        expect($run['status'])->not->toBe(0);
        expect($run['stdout'])
            ->toContain('PASS   target     environment_class production')
            ->toContain('FAIL   routing    delivery_mode held in mail-routing.json — not outbound')
            ->toContain('FAIL   direct     direct delivery is disabled on this host')
            ->toContain('PASS   mta        the reviewed public MTA hostname is mta1.tits.guru')
            ->toContain('FAIL   key        /etc/opendkim/keys/tits-guru/rg1.private is not usable: it does not exist')
            ->toContain('FAIL   signing    no DKIM signing service is installed and verified on this host')
            ->toContain('OUTBOUND READY: NO')
            ->not->toContain('OUTBOUND READY: YES');
    } finally {
        mailIdentityCleanup($scratch);
    }
});

it('passes every identity, key and DNS condition for a prepared outbound target, and still refuses without a signing service', function () {
    $scratch = mailIdentityScratch();

    try {
        $files = mailIdentityFixtureConfig($scratch.'/config', [
            'mode' => 'outbound',
            'outbound' => ['schema_version' => 1, 'direct' => ['enabled' => true, 'mta_hostname' => 'mta1.example.net']],
        ]);
        $key = mailIdentityInstallKey($scratch, 'demo-shop', 'shop2026');

        $run = mailIdentityRun(
            ['readiness', '--target', 'demo-shop', ...$files],
            mailIdentityDnsHost($scratch, mailIdentityGoodDns(mailIdentityPublicKey($key), '203.0.113.10', 'demo-shop.example', 'shop2026', 'mta1.example.net')),
        );

        expect($run['status'])->not->toBe(0);

        // Every condition this release can judge passes; exactly one fails.
        preg_match_all('/^  FAIL   (\S+)/m', $run['stdout'], $failures);
        expect($failures[1])->toBe(['signing']);
        expect($run['stdout'])
            ->toContain('PASS   routing    delivery_mode outbound')
            ->toContain('PASS   direct     direct delivery is enabled on this host as mta1.example.net')
            ->toContain('PASS   key        /etc/opendkim/keys/demo-shop/shop2026.private is a usable 2048-bit RSA private key')
            ->toContain('PASS   dkim')
            ->toContain('OUTBOUND READY: NO');

        // And without its key, the target is not ready on that count as well.
        unlink($key);
        $missing = mailIdentityRun(['readiness', '--target', 'demo-shop', ...$files], mailIdentityDnsHost($scratch, []));
        expect($missing['stdout'])->toContain('FAIL   key        /etc/opendkim/keys/demo-shop/shop2026.private is not usable: it does not exist');
    } finally {
        mailIdentityCleanup($scratch);
    }
});

// =============================================================================
// THE ROADMAP KEEPS THE REMAINING MAIL WORK APART
// =============================================================================

it('records the identity foundation and keeps the remaining mail work in its own slices', function () {
    $roadmap = preg_replace('/\s+/', ' ', File::get(base_path('infrastructure/ROADMAP.md')));

    expect($roadmap)
        ->toContain('**8.4B.4.1 Production mail identity foundation — IMPLEMENTED, nothing activated.**')
        ->toContain('**8.4B.4.2 DKIM signing, DNS-ready activation and the first real delivery — planned.**')
        ->toContain('**8.4B.5 Bounce reception, reply routing and the support mailbox — planned.**')
        ->toContain('**8.4B.6 Suppression, delivery state and per-target metrics — planned.**')
        ->toContain('**8.4B.7 Mail operations, recovery and security acceptance — planned.**');
});
