<?php

namespace App\Exceptions\Translations;

use App\Support\TranslationEngine\Enums\TranslationErrorCode;
use DomainException;

/**
 * A background generation that was not started, read, saved or discarded, and
 * why, in words an administrator can act on. Nothing is sent to a provider
 * and nothing is written when one is thrown.
 *
 * A batch that does not exist, has expired, or belongs to someone else is
 * simply unavailable: the message never says which.
 */
final class CannotGenerateTranslationsException extends DomainException
{
    public const REASON_NOT_ALLOWED = 'not_allowed';

    public const REASON_UNKNOWN_LOCALE = 'unknown_locale';

    public const REASON_REFERENCE_LOCALE = 'reference_locale';

    public const REASON_NOTHING_MISSING = 'nothing_missing';

    public const REASON_ALREADY_RUNNING = 'already_running';

    public const REASON_UNAVAILABLE = 'unavailable';

    public const REASON_NOT_READY = 'not_ready';

    public const REASON_ENGINE_FAILED = 'engine_failed';

    public const REASON_DISPATCH_FAILED = 'dispatch_failed';

    public const REASON_STORE_UNAVAILABLE = 'store_unavailable';

    public const REASON_BUSY = 'busy';

    private function __construct(string $message, public readonly string $reason)
    {
        parent::__construct($message);
    }

    public static function becauseUserIsNotAllowed(): self
    {
        return new self('You may not edit project translations.', self::REASON_NOT_ALLOWED);
    }

    public static function becauseLocaleIsNotInstalled(): self
    {
        return new self('That language is not installed.', self::REASON_UNKNOWN_LOCALE);
    }

    public static function becauseLocaleIsTheReference(): self
    {
        return new self('English is the reference language. Change it in the content’s own editor.', self::REASON_REFERENCE_LOCALE);
    }

    public static function becauseNothingIsMissing(): self
    {
        return new self('Nothing is missing for this language.', self::REASON_NOTHING_MISSING);
    }

    public static function becauseAnotherAdministratorIsGenerating(string $language): self
    {
        return new self("{$language} translations are already being generated by another administrator. Try again when that generation finishes.", self::REASON_ALREADY_RUNNING);
    }

    public static function becauseTheBatchIsUnavailable(): self
    {
        return new self('These generated translations are no longer available. Reload the page to see the current state.', self::REASON_UNAVAILABLE);
    }

    public static function becauseTheSuggestionIsNotReady(): self
    {
        return new self('This suggestion is no longer available. Reload the page to review it.', self::REASON_NOT_READY);
    }

    public static function becauseTheEngineFailed(TranslationErrorCode $code): self
    {
        return new self(CannotSuggestTranslationException::messageFor($code), self::REASON_ENGINE_FAILED);
    }

    public static function becauseItCouldNotBeQueued(): self
    {
        return new self('Background generation could not be started. Try again.', self::REASON_DISPATCH_FAILED);
    }

    public static function becauseTheBatchIsBusy(): self
    {
        return new self('These generated translations are busy right now. Try again in a moment.', self::REASON_BUSY);
    }

    public static function becauseTheStoreIsUnavailable(): self
    {
        return new self('Background generation is unavailable right now. You can still translate items one at a time.', self::REASON_STORE_UNAVAILABLE);
    }
}
