[program:rateguru-staging-queue]
process_name=%(program_name)s_%(process_num)02d

directory=/home/www/rateguru/staging/current

command=/usr/bin/php8.5 artisan queue:work redis --queue=rateguru-staging --sleep=3 --tries=3 --timeout=120 --max-time=3600 --max-jobs=1000

user=rateguru-staging
numprocs=1

autostart=true
autorestart=true
startsecs=3
startretries=5

stopasgroup=true
killasgroup=true
stopwaitsecs=130

redirect_stderr=true
stdout_logfile=/home/www/rateguru/staging/shared/storage/logs/queue-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

environment=APP_ENV="staging"
