<x-filament-panels::page>
    {{--
        Filament renders its admin pages using its own pre-built CSS bundle
        (public/css/filament/filament/app.css), which is not regenerated by this
        app's Vite/Tailwind build and never scans this file for utility classes.
        Utility classes (spacing, colors, borders, rounding) therefore compute to
        nothing even though they're present in the markup — verified via computed
        styles, not just visually. Layout/visuals here use plain scoped CSS instead
        so they don't depend on that bundle happening to already contain the exact
        class we reach for.

        This <style> tag must stay inside this component's single root element
        (<x-filament-panels::page>), not as a sibling before it — Livewire requires
        exactly one root element per component view. A sibling here silently broke
        the form's two-way data binding: server-rendered values were correct (visible
        in the Livewire snapshot), but the actual <input> DOM nodes stayed empty
        because Livewire hydrated against the wrong root.
    --}}
    <style>
        .rg-preset-box {
            margin-bottom: 1.5rem;
            padding: 1rem;
            border-radius: 0.5rem;
            border: 1px solid #fde68a;
            background-color: #fffbeb;
        }
        .dark .rg-preset-box {
            border-color: #92400e;
            background-color: #451a03;
        }
        .rg-preset-title {
            font-size: 0.875rem;
            font-weight: 500;
            color: #92400e;
        }
        .dark .rg-preset-title {
            color: #fde68a;
        }
        .rg-preset-desc {
            margin-top: 0.25rem;
            font-size: 0.75rem;
            color: #b45309;
        }
        .dark .rg-preset-desc {
            color: #fcd34d;
        }
        .rg-preset-actions {
            margin-top: 0.75rem;
            display: flex;
            flex-wrap: wrap;
            gap: 0.5rem;
        }
        .rg-preset-btn {
            border-radius: 0.25rem;
            border: none;
            background-color: #fef3c7;
            padding: 0.25rem 0.75rem;
            font-size: 0.75rem;
            font-weight: 500;
            color: #78350f;
            cursor: pointer;
        }
        .rg-preset-btn:hover {
            background-color: #fde68a;
        }
        .dark .rg-preset-btn {
            background-color: #78350f;
            color: #fef3c7;
        }
        .dark .rg-preset-btn:hover {
            background-color: #92400e;
        }
    </style>

    <div class="rg-preset-box">
        <p class="rg-preset-title">Apply a preset</p>
        <p class="rg-preset-desc">
            Applying a preset will overwrite current project settings fields.
        </p>
        <div class="rg-preset-actions">
            @foreach(\App\Filament\Pages\ProjectSettingsPage::presetOptions() as $key => $label)
                <button
                    type="button"
                    wire:click="applyPreset(@json($key))"
                    wire:confirm="Apply preset '{{ $label }}'? This will overwrite current settings."
                    class="rg-preset-btn"
                >
                    {{ $label }}
                </button>
            @endforeach
        </div>
    </div>

    <form wire:submit="save">
        {{ $this->form }}

        <div style="margin-top: 2.5rem; display: flex; justify-content: flex-end;">
            <x-filament::button type="submit">
                Save settings
            </x-filament::button>
        </div>
    </form>
</x-filament-panels::page>
