<x-voting.source-options
    :post="$post"
    :current-value="$currentValue"
    :voting-disabled="$votingDisabled"
    :is-own-post="$isOwnPost"
    :error="$error"
    root-test-id="origin-voting"
    unavailable-test-id="origin-voting-unavailable"
    error-test-id="origin-voting-error"
    option-a-test-id="origin-vote-homemade"
    option-b-test-id="origin-vote-restaurant"
    option-a-value="homemade"
    option-b-value="restaurant"
/>
